### ISSUE TITLE
Any last minute suggestions and PRs you want to submit before 1.0

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#10]
comment here

**Comment by webdev03** [comment]
You might want to change the `name` in `package.json` to lowercase, here's what npm says:
> A package.json file must contain "name" and "version" fields. The "name" field contains your package's name, and must be lowercase and one word, and may contain hyphens and underscores. The "version" field must be in the form x.x.x and follow the semantic versioning guidelines .

**Comment by JaydenDev** [comment]
alright, fixing.

**Comment by JaydenDev** [comment]
fixed.

**Comment by webdev03** [comment]
@JaydenDev you should probably close this
