### ISSUE TITLE
2.0

### ISSUE THREAD

**Issue by hello-smile6** [JaydenDev/freecat#100]
I just noticed https://www.electronjs.org/docs/latest/api/crash-reporter and https://github.com/electron/mini-breakpad-server . Could there be a crash reporting server for Freecat?

**Comment by hello-smile6** [comment]
Maybe just run on localhost and save to a file?

**Comment by JaydenDev** [comment]
thats what issues r 4

**Comment by hello-smile6** [comment]
> thats what issues r 4

I know, but then it'd be easier to get data for debugging.

**Comment by JaydenDev** [comment]
make it write to a log.txt and have it uploadable.

**Comment by hello-smile6** [comment]
> make it write to a log.txt and have it uploadable.

I'll try later.

**Comment by JaydenDev** [comment]
btw this is issue #100

**Comment by hello-smile6** [comment]
> btw this is issue #100

It is! :)

**Comment by JaydenDev** [comment]
focus
     on
             tabs
   so i can

 release
        2.0

**Comment by hello-smile6** [comment]
> focus on tabs so i can
> 
> release 2.0

But tabs are hard! Can I _please_ copy code???

**Comment by JaydenDev** [comment]
fineeee, credit MystPi tho

**Comment by hello-smile6** [comment]
> fineeee, credit MystPi tho

Okay. I'll try to use native first.

**Comment by hello-smile6** [comment]
UGH! Tabs are only for MacOS.

**Comment by JaydenDev** [comment]
what? they work on win and mac as wel.

**Comment by hello-smile6** [comment]
> what? they work on win and mac as wel.

No, I mean the API that lets you create tabs in Electron.

**Comment by JaydenDev** [comment]
thats not what Ninetails uses...

**Comment by JaydenDev** [comment]
also what did I say about avoiding APIs at all costs

**Comment by hello-smile6** [comment]
> also what did I say about avoiding APIs at all costs

Everything is an API. If I avoided APIs, I'd be avoiding everything but a 0-byte production build.

**Comment by JaydenDev** [comment]
Just use HTML and Javascript as well as electron non-APIs

**Comment by JaydenDev** [comment]
buttons that load and reload respective webviews!

**Comment by JaydenDev** [comment]
*and unload

**Comment by hello-smile6** [comment]
> Just use HTML and Javascript as well as electron non-APIs

Okay. Just saying, tabs are going to be really hard. Also, I'm working on a reload button.

**Comment by hello-smile6** [comment]
@JaydenDev Figured out how to make a settings page, should I make the UI to go with it and implement it?

**Comment by JaydenDev** [comment]
but... tabs :( need
i gotta have at least 1 feature in 2.0 
tabs are required for a good experience

SETTINGS go in 3.0, this is 2.0 development. Tabs, fine use an API if you have to .

**Comment by JaydenDev** [comment]
I am mainly better with OTHER coding languages than JS and UI design

**Comment by hello-smile6** [comment]
> but... tabs :( need i gotta have at least 1 feature in 2.0 tabs are required for a good experience
> 
> SETTINGS go in 3.0, this is 2.0 development. Tabs, fine use an API if you have to .

Couldn't having settings be the 2.0 feature?

**Comment by JaydenDev** [comment]
nah im already days behind on schedule for 2.0

**Comment by JaydenDev** [comment]
i release major releases weekly, when the previous release is about to hit 7 days old I better hurry up and release.

**Comment by hello-smile6** [comment]
> nah im already days behind on schedule for 2.0

Well, going for settings instead of tabs would get you back on schedule and make people happy. I could probably get a settings page with about 30-40 options done in an hour.

**Comment by JaydenDev** [comment]
fine take code use APIs whatever you need to do to make tabs and let me release 2.0

**Comment by JaydenDev** [comment]
fine settings cool i just need features for 2.0 eeek

**Comment by JaydenDev** [comment]
You need tabs to make a browser usable
I couldn't use ninetails til they added tabs.

**Comment by hello-smile6** [comment]
> You need tabs to make a browser usable I couldn't use ninetails til they added tabs.

IE didn't have tabs for years.

**Comment by JaydenDev** [comment]
however will you multi task

**Comment by JaydenDev** [comment]
all browsers need tabs in this day and age. pleaseee

**Comment by hello-smile6** [comment]
> all browsers need tabs in this day and age. pleaseee

If you want tabs, just run two copies.

**Comment by JaydenDev** [comment]
thats not efficient. I currently have 4 tabs now. Everything is small and hard to read cuz i have 4 FF windows open.

**Comment by JaydenDev** [comment]
I usually have around 8 for software devel

**Comment by hello-smile6** [comment]
Okay, I get the point!

**Comment by JaydenDev** [comment]
![image](https://user-images.githubusercontent.com/92550746/146293763-9a773e49-5ee0-4ee0-a367-5af13cb563ee.png)
artist depiction

**Comment by JaydenDev** [comment]
tabs ARE needed

**Comment by JaydenDev** [comment]
fine I'll try and get tabs working you do settings.

**Comment by hello-smile6** [comment]
I have 59 tabs open. Beat that.

**Comment by JaydenDev** [comment]
this is way too complicated for me
follow this
https://ourcodeworld.com/articles/read/925/how-to-implement-browser-like-tabs-in-electron-framework

**Comment by hello-smile6** [comment]
> this is way too complicated for me follow this https://ourcodeworld.com/articles/read/925/how-to-implement-browser-like-tabs-in-electron-framework

Same for me. Also, it's outdated and recommends using something that clearly wouldn't work very well.

**Comment by JaydenDev** [comment]
also webdev03 has some suggestions for you

![image](https://user-images.githubusercontent.com/92550746/146294105-a99d36f6-54db-4e47-83d6-7c13c068b525.png)

**Comment by hello-smile6** [comment]
> also webdev03 has some suggestions for you
> 
> ![image](https://user-images.githubusercontent.com/92550746/146294105-a99d36f6-54db-4e47-83d6-7c13c068b525.png)

Post ID? I wanna reply.

**Comment by JaydenDev** [comment]
I have to go, i'll be back in an hour.

**Comment by hello-smile6** [comment]
> I have to go, i'll be back in an hour.

Okay.

**Comment by JaydenDev** [comment]
@hello-smile6 its in the ninetails topic
i'd suggest talking in the FreeCat topic

brb

**Comment by hello-smile6** [comment]
> I have to go, i'll be back in an hour.

You'll come back to reload, back, and forward buttons, most likely.

**Comment by JaydenDev** [comment]
back

**Comment by hello-smile6** [comment]
> back

Okay, I've gotten a working reload button and am working on back and forward buttons!

**Comment by JaydenDev** [comment]
ima make tabs I guess :<

```
let tabcount = 0;
function newtab {
  let tabcount = tabcount + 1;
  let tab01 = tabcount + btn;
  ```

i give up idk

**Comment by hello-smile6** [comment]
> ima make tabs I guess :<
> 
> ```
> let tabcount = 0;
> function newtab {
>   let tabcount = tabcount + 1;
>   let tab01 = tabcount + btn;
> ```
> 
> i give up idk

Why not store an array in localStorage and erase it when the window opens if it's been closed for more than 5 seconds, then go with a bookmarks-style approach?

**Comment by JaydenDev** [comment]
I know nothing about arrays i was gunna

tabcount = num of tabs
create a button named value of tab count + btn
create a btn

have the btn run a function that hides/shows respective webviews

**Comment by JaydenDev** [comment]
I use way less efficient methods with what I know about JS
plus i cant get local storage to work its hard

**Comment by hello-smile6** [comment]
> I use way less efficient methods with what I know about JS plus i cant get local storage to work its hard

`localStorage` is simple. Treat it like an array that can only store strings and numbers.

**Comment by JaydenDev** [comment]
i do things the least practical ways with the basic knowlege i have

**Comment by JaydenDev** [comment]
i cant ever get localStorage to work.
"A browser will always suck if JaydenDev's code is in it" - Every dev ever

**Comment by JaydenDev** [comment]
I can't do any back end, I gotta let everyone else handle that and me handle the front end. The most HTML/CSS/JS i've done was front end web development.

**Comment by hello-smile6** [comment]
> i cant ever get localStorage to work. "A browser will always suck if JaydenDev's code is in it" - Every dev ever

Here's an example.
```javascript
if(typeof localStorage.tabs!=="string") {
  localStorage.tabs="[]";
}
function savePage(url) {
  localStorage.tabs=JSON.stringify(JSON.parse(localStorage.tabs).push(url);
}
function getPage(index) {
  // Arrays start at 0 for index
  return JSON.parse(localStorage.tabs)[index];
}
```

**Comment by JaydenDev** [comment]
im a front end web developer

**Comment by JaydenDev** [comment]
heck it is

I can handle UI thats about it

**Comment by hello-smile6** [comment]
> heck it is
> 
> I can handle UI thats about it

It isn't backend! Also, should the URL bar stay focused when the user presses enter?

**Comment by JaydenDev** [comment]
well the URL bar doesn't support using ENTER to search

**Comment by hello-smile6** [comment]
> well the URL bar doesn't support using ENTER to search

Can we use the regex Ninetails uses?

**Comment by JaydenDev** [comment]
ask MystPi for permission

**Comment by hello-smile6** [comment]
> ask MystPi for permission

I'll find a different regex online, then.

**Comment by JaydenDev** [comment]
you gotta ask the original devs

**Comment by hello-smile6** [comment]
Why not use the regex that the SA "More links" addon uses, if it uses one?

**Comment by JaydenDev** [comment]
are you working on tabs? i gotta know what ur doin to answer questions
but why regex for tabs...?
what is regex anyway?

**Comment by hello-smile6** [comment]
> are you working on tabs? i gotta know what ur doin to answer questions but why regex for tabs...? what is regex anyway?

Regular expression. I'm trying to make it possible to enter search queries in the URL bar.

**Comment by JaydenDev** [comment]
oh... nobody is gonna be using freecat til tabs are added just so you know.

**Comment by JaydenDev** [comment]
just do if the input contains https:// use the URL but if it doesn't use https:// then just search.

**Comment by hello-smile6** [comment]
> just do if the input contains https:// use the URL but if it doesn't use https:// then just search.

Okay.

**Comment by JaydenDev** [comment]
i mean its really that simple just a thousand if/else expressions

**Comment by JaydenDev** [comment]
also make sure to implement http support as well

**Comment by hello-smile6** [comment]
> also make sure to implement http support as well

Okay.

**Comment by JaydenDev** [comment]
so umm...
tabs how

**Comment by hello-smile6** [comment]
> so umm... tabs how

Not sure. :(

**Comment by JaydenDev** [comment]
![index](https://user-images.githubusercontent.com/92550746/146298409-22d9fe71-2160-411b-ab56-99dc1174be4d.png)
this is what i want in the future

**Comment by JaydenDev** [comment]
you can probobly guess what each feature and the placement is

**Comment by JaydenDev** [comment]
![image](https://user-images.githubusercontent.com/92550746/146298504-13abeb7d-975f-44af-9b9b-64469212f552.png)
better image

**Comment by hello-smile6** [comment]
I think I got forward and back to work (partially)!

**Comment by JaydenDev** [comment]
i guess just finish the back forward and reloading and we'll implement tabs and settings in 3.0

**Comment by JaydenDev** [comment]
that way there will be a week to implement them

**Comment by hello-smile6** [comment]
> i guess just finish the back forward and reloading and we'll implement tabs and settings in 3.0

I like the sound of that, but let's put settings in 2.0!

**Comment by JaydenDev** [comment]
nobody will use freecat til tabs are added so

**Comment by JaydenDev** [comment]
@hello-smile6 i have to release 2.0 TODAY im already behind schedule

**Comment by hello-smile6** [comment]
> @hello-smile6 i have to release 2.0 TODAY im already behind schedule

Okay, I'll have it soon.

**Comment by JaydenDev** [comment]
3 days behind.... gotta release today

**Comment by JaydenDev** [comment]
i have til 10:00 PM CST
preferably earlier as i gotta go 2 bed

**Comment by hello-smile6** [comment]
Status:

- [ ] Back button working
- [ ] Forward button working
- [ ] Reload button working
- [ ] Settings working
- [ ] Making PR

**Comment by JaydenDev** [comment]
but.. but...

**Comment by hello-smile6** [comment]
> but.. but...

I'm trying! I'm only one person!

**Comment by JaydenDev** [comment]
we used to have 3 ppl actively developing

they all left

**Comment by hello-smile6** [comment]
> we used to have 3 ppl actively developing
> 
> they all left

I know. :(

**Comment by JaydenDev** [comment]
and my coding sux

**Comment by hello-smile6** [comment]
But, just saying, Freecat is ahead of Ninetails in number of commits **and** number of lines added, and is behind in number of lines deleted, which is good. :)

**Comment by hello-smile6** [comment]
3 of 5 goals complete!

**Comment by JaydenDev** [comment]
totally not AI generated
Here is why tabs are important. 

First, they improve the performance. It’s pretty obvious that tabs improve the performance but I believe it deserves an explanation. When a user opens a tab, he/she has to close the last tab. When a user is in a particular page, he/she can close all the tabs. Also, if a user goes to a particular bookmark, he/she has to close all the tabs before opening that bookmark. And, if a user opens multiple tabs, he/she will have to close all the tabs before the bookmark.

Thanks to the tabs, it reduces the performance of the browser. This doesn’t only apply for Google Chrome but all other browsers such as Opera, Mozilla, etc.

Second, it saves space. By using the tabs, you can use your web browser, for example, Google Chrome as a portable app. When you open a webpage, you can use any of the web browsers, for example, Firefox, Opera, etc.

Any one of the web browsers will open a page. When you open multiple tabs, you can save the space and use it in other ways, for example, writing notes.

Now that you have got all the benefits of using tabs, how can you convert to tabs. Well, all the browsers have already got this feature. It can be accessed in the toolbar of the tabs of the browsers. It’s on the top right corner of the tab bar. I will list out the screenshots of the aforementioned tabs of Google Chrome below.

Check it out!

All the tabs have been converted to tabs.

These were just some of the advantages of using tabs. Let me know if you know anything else

**Comment by JaydenDev** [comment]
> 3 of 5 goals complete!

3 of 6

**Comment by hello-smile6** [comment]
> > 3 of 5 goals complete!
> 
> 3 of 6

Fine 🙂

**Comment by JaydenDev** [comment]
> > > 3 of 5 goals complete!
> > 
> > 
> > 3 of 6
> 
> Fine 🙂

the one i added was "Question the meaning of life", its an important task.

**Comment by JaydenDev** [comment]
hows the development going

**Comment by hello-smile6** [comment]
> > > > 3 of 5 goals complete!
> > > 
> > > 
> > > 3 of 6
> > 
> > 
> > Fine 🙂
> 
> the one i added was "Question the meaning of life", its an important task.

Um, that'd take about 30 lifetimes, so that'd put Freecat 156000 releases behind. Sorry!

**Comment by JaydenDev** [comment]
it was a joke..

**Comment by hello-smile6** [comment]
> it was a joke..

I know! :) And also,
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\hello-smile6> node
Welcome to Node.js v17.2.0.
Type ".help" for more information.
> 30*52*100
156000
>
```
I actually checked.

**Comment by JaydenDev** [comment]
dont use node v17 thats not a stable release yet. its not even production

**Comment by hello-smile6** [comment]
> dont use node v17 thats not a stable release yet. its not even production

It is stable! It's just not LTS. Sorry, but LTS is the next best thing to deprecated.

**Comment by JaydenDev** [comment]
LTS versions of node are recommended

**Comment by hello-smile6** [comment]
> LTS versions of node are recommended

To quote you:

> but.. but...

I like new features.

**Comment by JaydenDev** [comment]
tabs

**Comment by hello-smile6** [comment]
> btw freecat performs better than ninetails

That's what I said on `https://github.com/MystPi/ninetails/pull/49#pullrequestreview-833555940` !

**Comment by JaydenDev** [comment]
thats not neccesary

**Comment by hello-smile6** [comment]
> thats not neccesary

Just having fun! 😦

**Comment by JaydenDev** [comment]
thats not how marketing works

**Comment by hello-smile6** [comment]
> thats not how marketing works

Well, Intel put false test results supposedly from Apple's M1 MacBook Pro devices in ads, so why can't I put completely truthful information in a pull request comment?

**Comment by JaydenDev** [comment]
do you think Microsoft just puts "Google sucks" in their bing ADs?

**Comment by JaydenDev** [comment]
people use Ninetails it has a community it has features
freecat is a dumpster fire

but freecat is more community oriented

**Comment by hello-smile6** [comment]
> do you think Microsoft just puts "Google sucks" in their bing ADs?

They might as well, as long as they back it up with evidence.

**Comment by hello-smile6** [comment]
> people use Ninetails it has a community it has features freecat is a dumpster fire
> 
> but freecat is more community oriented

Freecat is **not** a dumpster fire! The number of people who noticed my rickroll easily proves that!

**Comment by JaydenDev** [comment]
if nobody uses it
its for a reason

**Comment by JaydenDev** [comment]
i'll just have to add telemetry and find out how many ppl use it *jk*

**Comment by hello-smile6** [comment]
> if nobody uses it its for a reason

Um, releases are now working. Also, we're heading for having more features than ninetails.

**Comment by hello-smile6** [comment]
> i'll just have to add telemetry and find out how many ppl use it _jk_

Just use my `rr-tracker`. Here's what you have to do.
```javascript
fetch("https://rr-tracker.9pfs.repl.co/freecat-analytics");
```
It doesn't log most of the time, which helps a bit with privacy issues.

**Comment by JaydenDev** [comment]
yeah no im against data collection and telemetry

**Comment by hello-smile6** [comment]
Then what's that entry in the repo insights page that shows who's opened what pages?

**Comment by JaydenDev** [comment]
WHO DID THAT!?

**Comment by JaydenDev** [comment]
SOMEBODY IS GOING TO BE FIRED

**Comment by hello-smile6** [comment]
> WHO DID THAT!?

GitHub did. 🙂

**Comment by JaydenDev** [comment]
time to sue github

**Comment by JaydenDev** [comment]
just kidding, btw tabs

**Comment by hello-smile6** [comment]
> time to sue github

Just hit up goo.gl for a few billion. GA's a better target.

**Comment by JaydenDev** [comment]
how bout i just

TABS

**Comment by hello-smile6** [comment]
> how bout i just
> 
> TABS

How about... Settings is nearly done!

**Comment by JaydenDev** [comment]
THEN tabs

**Comment by hello-smile6** [comment]
> THEN tabs

Okay.

**Comment by JaydenDev** [comment]
tabs are required for any browser

**Comment by JaydenDev** [comment]
gotta catch up with ninetails

**Comment by hello-smile6** [comment]
> tabs are required for any browser

Tell `links` that.

**Comment by JaydenDev** [comment]
multitasking need

**Comment by hello-smile6** [comment]
I gotta make a PR on https://github.com/MystPi/DreamCSS

**Comment by JaydenDev** [comment]
- [ ] settings
- [ ] tabs

**Comment by JaydenDev** [comment]
gh decided to hide the last one

**Comment by hello-smile6** [comment]
Settings: half checked.

**Comment by JaydenDev** [comment]
I haven't seen your UI design  yet, it might suck. Screenshot?

**Comment by hello-smile6** [comment]
> I haven't seen your UI design yet, it might suck. Screenshot?

I'll put it on a gh gist

**Comment by JaydenDev** [comment]
no just copy paste

**Comment by hello-smile6** [comment]
Too late, already done.
https://gist.github.com/hello-smile6/2ece2819df39b2b7f4c12434fb65daf3

**Comment by hello-smile6** [comment]
Don't judge, I'm working on it.

**Comment by JaydenDev** [comment]
screenshot?

**Comment by hello-smile6** [comment]
> screenshot?

In a minute

**Comment by JaydenDev** [comment]
25 minutes left!

**Comment by hello-smile6** [comment]
> 25 minutes left!

Okay

**Comment by hello-smile6** [comment]
What's our default search provider?

**Comment by JaydenDev** [comment]
DDG

**Comment by hello-smile6** [comment]
> DDG

URL, with %s in the place of search query?

**Comment by JaydenDev** [comment]
idk how duck duck go does it hold on

**Comment by JaydenDev** [comment]
https://duckduckgo.com/?q=a&t=h_&ia=web
im pretty sure its complicated...

**Comment by hello-smile6** [comment]
Got it. Thanks.

**Comment by JaydenDev** [comment]
its ?q instead of %s
?q=search

**Comment by JaydenDev** [comment]
time is tickin
its a time bomb
gotta release 2.0 soon

**Comment by hello-smile6** [comment]
> time is tickin its a time bomb gotta release 2.0 soon

Nearly done.

**Comment by JaydenDev** [comment]
k

**Comment by JaydenDev** [comment]
i feel like even at release 100.0 you still wont have figured out the tab situation

**Comment by hello-smile6** [comment]
IT WORKS! Making a commit and PR.

**Comment by JaydenDev** [comment]
what features did you pack in

**Comment by hello-smile6** [comment]
> what features did you pack in

Back and forward buttons, settings button, reload button, some changes to dreamcss. In other words, a lot. Also, I'm making a quick change that'll take less than 5 min.

**Comment by JaydenDev** [comment]
so tabs in 3.0? you'll have an entire week to develop and experiment

**Comment by JaydenDev** [comment]
make sure to polish and fix code to get ready for 2.0 release today!

**Comment by JaydenDev** [comment]
full dream.css implementation? dont completely copy the ninetails UI

**Comment by hello-smile6** [comment]
> full dream.css implementation? dont completely copy the ninetails UI

It's ready, I used dream.css on the settings page and homepage.

**Comment by JaydenDev** [comment]
home.. page? oh

**Comment by hello-smile6** [comment]
See #104

**Comment by JaydenDev** [comment]
never base it off a broken branch LMAO

**Comment by hello-smile6** [comment]
> never base it off a broken branch LMAO

Sorry. Also, done. #105

**Comment by JaydenDev** [comment]
@hello-smile6 
1. Never use testing branch
2. Prettier breaks FreeCat, don't use it.

**Comment by JaydenDev** [comment]
@hello-smile6 
can you redo your reload/back/forward button PR and make it WITHOUT prettier on the MAIN branch!!!!!!!!!!!!!!!!!

**Comment by hello-smile6** [comment]
> @hello-smile6 can you redo your reload/back/forward button PR and make it WITHOUT prettier on the MAIN branch!!!!!!!!!!!!!!!!!

Sure.

**Comment by hello-smile6** [comment]
> > > @hello-smile6 can you redo your reload/back/forward button PR and make it WITHOUT prettier on the MAIN branch!!!!!!!!!!!!!!!!!
> > 
> > 
> > Sure.
> 
> Good

Can't find any breaking commits.

**Comment by JaydenDev** [comment]
@hello-smile6 
I already reverted to the last reverting build
just remake the PR

**Comment by JaydenDev** [comment]
https://github.com/JaydenDev/Catalyst
Move to Catalyst
