### ISSUE TITLE
I have to rename FreeCat, there is already a project named FreeCat

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#106]
Some names I had in mind:

Zap
Tab
ElegantHTML
Chromi (i kinda like this one)
Zen (I plan on making an operating system with this name...)

**Comment by VelocityDesign** [comment]
Catalyst Browser would be a good name. You can make any customizations you'd like, but the underlying browser and license stay the same (Making it the catalyst.)

**Comment by JaydenDev** [comment]
> Catalyst Browser would be a good name. You can make any customizations you'd like, but the underlying browser and license stay the same (Making it the catalyst.)

Hmm, interesting but is there another project with that name.

**Comment by ScolderCreations** [comment]
‘Artweb’?

**Comment by JaydenDev** [comment]
> ‘Artweb’?

The heck is that

**Comment by ScolderCreations** [comment]
> > ‘Artweb’?
> 
> The heck is that

Well, I thought it might fit for a customizable browser. The other names I thought of might be better though.

**Comment by JaydenDev** [comment]
> ideas:
> ‘Artweb’
> ‘Browsimorph’
> ‘FreeFly’
> ‘Exprowse’

Those are all awfully weird

**Comment by JaydenDev** [comment]
I will either settle on Catalyst or Zen
Please take a look at #108 though

**Comment by VelocityDesign** [comment]
I wouldn't do chromi due to the closeness to chrome

**Comment by ScolderCreations** [comment]
> > I wouldn't do chromi due to the closeness to chrome
> 
> Well it's chrome-like already Would ChromiZen be good?

That sounds like some sort of editor. I think Catalyst would work.

**Comment by JaydenDev** [comment]
> > > I wouldn't do chromi due to the closeness to chrome
> > 
> > Well it's chrome-like already Would ChromiZen be good?
> 
> That sounds like some sort of editor. I think Catalyst would work.
It's too obscure and weird.

Plus their is AMD Catalyst software

**Comment by VelocityDesign** [comment]
Hmm
Maybe do an art-related name (Like Vivaldi, etc.)

**Comment by JaydenDev** [comment]
This is not art, lets not use an art related name.

I might just settle on Zen, Catalyst, Chromi, or ChromiZen

**Comment by JaydenDev** [comment]
I need an icon to go with these as well

**Comment by JaydenDev** [comment]
# Catalyst
## Icon Details
Colors: Purple, Blue, Green
Style: Swirls

# Zen
## Icon Details
Colors: Blue, Light Blue, Green
Style: Swirls

# ChromiZen
## Icon Details
Colors: Chrome Colors, Blue, Green
Style: Chrome + Swirls

**Comment by JaydenDev** [comment]
Also, everyone please focus more on #108, it's more critical of an issue.

**Comment by kccuber-scratch** [comment]
ElectroBrowser, cringy but works

**Comment by JaydenDev** [comment]
> ElectroBrowser, cringy but works
> EDIT: Or ElectroCat

Both bad

**Comment by VelocityDesign** [comment]
I don't know anything about electron stuff lol

**Comment by JaydenDev** [comment]
> I don't know anything about electron stuff lol

ChromiZen or Catalyst

**Comment by VelocityDesign** [comment]
I really don't like ChromiZen. It's as bad as ElectroCat. Zen Browser sounds cool and could go with your OS project. Either way, from a brand standpoint I can help with that. I do design, etc.

**Comment by JaydenDev** [comment]
> I really don't like ChromiZen. It's as bad as ElectroCat. Zen Browser sounds cool and could go with your OS project. Either way, from a brand standpoint I can help with that. I do design, etc.

Catalyst with the icon design I recommended for the name could work. But for now let's fix #108

**Comment by VelocityDesign** [comment]
Portfolio (Haven't updated in a bit): https://dribbble.com/velocitydev

**Comment by JaydenDev** [comment]
@VelocityDesign 
Could you make a concept icon for the "Catalyst" idea.
I put what details and colors i want listed below

# Catalyst
## Icon Details
Colors: Purple, Blue, Green
Style: Swirls

**Comment by snowcatridge10** [comment]
Catalyst is cool

**Comment by VelocityDesign** [comment]
> @VelocityDesign Could you make a concept icon for the "Catalyst" idea. I put what details and colors i want listed below
> 
> # Catalyst
> ## Icon Details
> Colors: Purple, Blue, Green Style: Swirls

I can have it done for you sometime tonight :)

**Comment by JaydenDev** [comment]
> > @VelocityDesign Could you make a concept icon for the "Catalyst" idea. I put what details and colors i want listed below
> > 
> > # Catalyst
> > ## Icon Details
> > Colors: Purple, Blue, Green Style: Swirls
> 
> I can have it done for you sometime tonight :)

Ok

**Comment by 3quarterscolon** [comment]
> I really don't like ChromiZen. It's as bad as ElectroCat. Zen Browser sounds cool and could go with your OS project. Either way, from a brand standpoint I can help with that. I do design, etc.

I agree.
I think ElectroCat is actually better than ChromiZen, because it has a meaning (and easily a mascot as well) and feels less cold and clinical. Catalyst is still the way to go, though.

**Comment by VelocityDesign** [comment]
I'm working on electron-forge as soon as i get the logo done.

**Comment by VelocityDesign** [comment]
![catalyst](https://user-images.githubusercontent.com/24457862/146663821-07ec9af2-eaab-4a9d-b6e6-4aa45fc7c64f.png)
Here we go!

**Comment by hello-smile6** [comment]
> ![catalyst](https://user-images.githubusercontent.com/24457862/146663821-07ec9af2-eaab-4a9d-b6e6-4aa45fc7c64f.png) Here we go!

I'll get it set up

**Comment by VelocityDesign** [comment]
> > ![catalyst](https://user-images.githubusercontent.com/24457862/146663821-07ec9af2-eaab-4a9d-b6e6-4aa45fc7c64f.png) Here we go!
> 
> I'll get it set up

I'm adding it to the Electron-forge contrib.

**Comment by JaydenDev** [comment]
That's an amazing icon... Yes thats good, how to add it to the app idk Ninetails has it working for the window title bar but not Linux task bars

**Comment by JaydenDev** [comment]
Btw @VelocityDesign please go to the Catalyst repo

**Comment by JaydenDev** [comment]
JaydenDev/Catalyst

**Comment by JaydenDev** [comment]
Move to the Catalyst Repo
https://github.com/JaydenDev/Catalyst
