### ISSUE TITLE
A better system...

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#107]
Instead of just me deciding on what PRs get merged, the community will be referred to from time to time. To prevent FreeCat from going into a direction that people don't want.

**Comment by JaydenDev** [comment]
I don't want FreeCat to be an entirely single opinion, one person controlled piece of software. The whole thing that FreeCat is, not to have good features, not to be the best of the best. But rather to be customizable, private, safe, and community driven.

**Comment by kccuber-scratch** [comment]
I agree, hello-smile6 broke a whole bunch of stuff and made freecat go in weird directions. like whats with the double license thing

**Comment by JaydenDev** [comment]
It's a mess ik

**Comment by hello-smile6** [comment]
> I agree, hello-smile6 broke a whole bunch of stuff and made freecat go in weird directions. like whats with the double license thing oh my now it's GPLv3, what the heck is going on

I didn't break things. I actually added some features.

**Comment by JaydenDev** [comment]
> > I agree, hello-smile6 broke a whole bunch of stuff and made freecat go in weird directions. like whats with the double license thing oh my now it's GPLv3, what the heck is going on
> 
> I didn't break things. I actually added some features.

You broke freecat twice with prettier
Added repo bloat and unneeded GitHub features

You made a mess, the only feature your added was a PR that broke freecat because you decided to use prettier like you weren't supposed to

**Comment by hello-smile6** [comment]
> > > I agree, hello-smile6 broke a whole bunch of stuff and made freecat go in weird directions. like whats with the double license thing oh my now it's GPLv3, what the heck is going on
> > 
> > 
> > I didn't break things. I actually added some features.
> 
> You broke freecat twice with prettier Added repo bloat and unneeded GitHub features
> 
> You made a mess, the only feature your added was a PR that broke freecat because you decided to use prettier like you weren't supposed to

I didn't use it. Check the prettier workflow results.

**Comment by JaydenDev** [comment]
Well I removed everything formatting related, go ahead and remake the PR.

**Comment by hello-smile6** [comment]
> Well I removed everything formatting related, go ahead and remake the PR.

Okay

**Comment by JaydenDev** [comment]
Prettier caused a heck of a lot of problems...

**Comment by hello-smile6** [comment]
> Prettier caused a heck of a lot of problems...

I agree. Feel like every Prettier config file there is needs to be added to <a href="https://github.com/JaydenDev/freecat/blob/main/.gitignore">`.gitignore`</a>.

**Comment by hello-smile6** [comment]
> > Prettier caused a heck of a lot of problems...
> 
> I agree. Feel like every Prettier config file there is needs to be added to [`.gitignore`](https://github.com/JaydenDev/freecat/blob/main/.gitignore).

@JaydenDev Implemented in #109

**Comment by JaydenDev** [comment]
> > > Prettier caused a heck of a lot of problems...
> > 
> > I agree. Feel like every Prettier config file there is needs to be added to [`.gitignore`](https://github.com/JaydenDev/freecat/blob/main/.gitignore).
> 
> @JaydenDev Implemented in #109 

Go ahead and include you're features as well
Forward back and reload buttons
Test them completely, base it of main, and don't use prettier

**Comment by hello-smile6** [comment]
> > > > Prettier caused a heck of a lot of problems...
> > > 
> > > 
> > > I agree. Feel like every Prettier config file there is needs to be added to [`.gitignore`](https://github.com/JaydenDev/freecat/blob/main/.gitignore).
> > 
> > 
> > @JaydenDev Implemented in #109
> 
> Go ahead and include you're features as well Forward back and reload buttons Test them completely, base it of main, and don't use prettier

Okay. Also, #110 fixes the license.

**Comment by JaydenDev** [comment]
> > > > > Prettier caused a heck of a lot of problems...
> > > > 
> > > > 
> > > > I agree. Feel like every Prettier config file there is needs to be added to [`.gitignore`](https://github.com/JaydenDev/freecat/blob/main/.gitignore).
> > > 
> > > 
> > > @JaydenDev Implemented in #109
> > 
> > Go ahead and include you're features as well Forward back and reload buttons Test them completely, base it of main, and don't use prettier
> 
> Okay. Also, #110 fixes the license.

Change the entire license to MIT

**Comment by hello-smile6** [comment]
> > > > Prettier caused a heck of a lot of problems...
> > > 
> > > 
> > > I agree. Feel like every Prettier config file there is needs to be added to [`.gitignore`](https://github.com/JaydenDev/freecat/blob/main/.gitignore).
> > 
> > 
> > @JaydenDev Implemented in #109
> 
> Go ahead and include you're features as well Forward back and reload buttons Test them completely, base it of main, and don't use prettier

Think you went a bit too far back, `home.html` is now back to not using dreamcss

**Comment by hello-smile6** [comment]
> > > > > > Prettier caused a heck of a lot of problems...
> > > > > 
> > > > > 
> > > > > I agree. Feel like every Prettier config file there is needs to be added to [`.gitignore`](https://github.com/JaydenDev/freecat/blob/main/.gitignore).
> > > > 
> > > > 
> > > > @JaydenDev Implemented in #109
> > > 
> > > 
> > > Go ahead and include you're features as well Forward back and reload buttons Test them completely, base it of main, and don't use prettier
> > 
> > 
> > Okay. Also, #110 fixes the license.
> 
> Change the entire license to MIT

That's what #110 does.

**Comment by JaydenDev** [comment]
I don't merge PRs till I'm off my break and at the computer

**Comment by hello-smile6** [comment]
I'm trying to undo the revert on my `main` branch.

**Comment by JaydenDev** [comment]
> I'm trying to undo the revert and fix everything on my `main` branch.

Main branch was already fixed... Come on man you're breaking it again

**Comment by hello-smile6** [comment]
> > I'm trying to undo the revert and fix everything on my `main` branch.
> 
> Main branch was already fixed... Come on man you're breaking it again

Could you `git clone` my repository in a different directory and test it, then tell me if there are any errors?

**Comment by hello-smile6** [comment]
> > I'm trying to undo the revert and fix everything on my `main` branch.
> 
> Main branch was already fixed... Come on man you're breaking it again

I never used prettier on that PR.

**Comment by hello-smile6** [comment]
@JaydenDev Successful build, built binary execution, and development execution from <a href="https://github.com/hello-smile6/freecat/tree/5ed16f2e16138740af68193f10dc31c830584652-archive">`5ed16f`</a> , can you reproduce using the <a href="https://github.com/hello-smile6/freecat/archive/refs/heads/5ed16f2e16138740af68193f10dc31c830584652-archive.zip">`.zip`</a> from that commit?

**Comment by JaydenDev** [comment]
> @JaydenDev Successful build, built binary execution, and development execution from <a href="https://github.com/hello-smile6/freecat/tree/5ed16f2e16138740af68193f10dc31c830584652-archive">`5ed16f`</a> , can you reproduce using the <a href="https://github.com/hello-smile6/freecat/archive/refs/heads/5ed16f2e16138740af68193f10dc31c830584652-archive.zip">`.zip`</a> from that commit?

I'm on break...

**Comment by hello-smile6** [comment]
> > @JaydenDev Successful build, built binary execution, and development execution from [`5ed16f`](https://github.com/hello-smile6/freecat/tree/5ed16f2e16138740af68193f10dc31c830584652-archive) , can you reproduce using the [`.zip`](https://github.com/hello-smile6/freecat/archive/refs/heads/5ed16f2e16138740af68193f10dc31c830584652-archive.zip) from that commit?
> 
> I'm on break...

Okay, then when you're not?

**Comment by JaydenDev** [comment]
@hello-smile6  give me the zip

**Comment by hello-smile6** [comment]
> @hello-smile6 give me the zip

Okay. https://github.com/hello-smile6/freecat/archive/refs/heads/5ed16f2e16138740af68193f10dc31c830584652-archive.zip

**Comment by JaydenDev** [comment]
Is it compiled?

**Comment by JaydenDev** [comment]
@hello-smile6 getting builds working isn't a priority
FreeCat isn't even a stable browser yet

**Comment by JaydenDev** [comment]
FreeCat may go under an entire rewrite btw...

**Comment by JaydenDev** [comment]
if you dont stop messing up what is already had

**Comment by JaydenDev** [comment]
a new beginning...
at https://github.com/JaydenDev/Catalyst

**Comment by hello-smile6** [comment]
> a new beginning... at https://github.com/JaydenDev/Catalyst

What??? So, why not rename this repo?

**Comment by JaydenDev** [comment]
I'm making a complete rewrite, trying not to make another train wreck

**Comment by JaydenDev** [comment]
First off, can I have the actual URL bar, and forward back and reload in Electron instead of HTML

**Comment by JaydenDev** [comment]
talk here: https://github.com/JaydenDev/Catalyst/issues/1

**Comment by hello-smile6** [comment]
> First off, can I have the actual URL bar, and forward back and reload in Electron instead of HTML

It has to be in HTML, as the UI is HTML. Could you open discussions on that repo and create a new thread for feature migration?

**Comment by JaydenDev** [comment]
there is no feature migration
its all being redone
try not to make it an unstable sucky mess this time alright?

What styling...? Tailwind? What for the search bar
discuss i here: JaydenDev/Catalyst#1

**Comment by hello-smile6** [comment]
> there is no feature migration its all being redone try not to make it an unstable sucky mess this time alright?
> 
> What styling...? Tailwind? What for the search bar discuss i here: [JaydenDev/Catalyst#1](https://github.com/JaydenDev/Catalyst/issues/1)

Okay

**Comment by JaydenDev** [comment]
It's all @ https://github.com/JaydenDev/Catalyst
