### ISSUE TITLE
FreeCat broken by prettier

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#108]
What syntax error is causing this white screen

**Comment by webdev03** [comment]
Maybe open it up in VSCode?

**Comment by JaydenDev** [comment]
I dont use vscode I use vim
which ALSO has syntax highlighting.

And i cant find it
It's like what happened last time when nobody knew what was wrong.
I will have to revert to the last build and hope nobody is stupid enough to run prettier again.

**Comment by JaydenDev** [comment]
The only syntax errors detected:

![image](https://user-images.githubusercontent.com/92550746/146606566-ce2aaaba-0d12-4ae8-9d4c-7c16f91f2e8e.png)

**Comment by JaydenDev** [comment]
these are all false positives

**Comment by webdev03** [comment]
yes thats why I made an eslint config for you earlier.

**Comment by webdev03** [comment]
FYI: You didn't remove prettier.

**Comment by JaydenDev** [comment]
> yes thats why I made an eslint config for you earlier. and @hello-smile6 you should have asked jaydendev first. open up devtools

Lint tools shouldn't style rather fix errors

**Comment by webdev03** [comment]
yes that is what it is trying to do

**Comment by JaydenDev** [comment]
Dev tools don't open btw

**Comment by JaydenDev** [comment]
someone has to get on this issue :((((

**Comment by webdev03** [comment]
https://github.com/JaydenDev/freecat/blob/main/package.json#L30

**Comment by webdev03** [comment]
From which commit did this start @JaydenDev ?

**Comment by JaydenDev** [comment]
I can just revert to the last working build

**Comment by hello-smile6** [comment]
> The only syntax errors detected:
> 
> ![image](https://user-images.githubusercontent.com/92550746/146606566-ce2aaaba-0d12-4ae8-9d4c-7c16f91f2e8e.png)

I'll fix.
