### ISSUE TITLE
Release 1.1 Community Feature Poll

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#11]
The community gets to decide the features that will be developed and released in Release 1.1
Pick one!

1. History
2. Tabs
3. Bug Fixes

**Comment by webdev03** [comment]
3, and 2

**Comment by kccuber-scratch** [comment]
If I only get to pick one, it would probably be history, that should be added before tabs

**Comment by snowcatridge10** [comment]
Tabs

**Comment by snowcatridge10** [comment]
For tabs I recommend https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_tabs

**Comment by JaydenDev** [comment]
Looks like tabs win, I'll start working on them tomorrow. Bugs today, start reporting any bugs you find so I can make freecat more stable

Expect FreeCat 1.0-patch1a soon

**Comment by hello-smile6** [comment]
Yay! Tabs are important!
