### ISSUE TITLE
Discuss

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#12]
1. Make the search bar and go button on same line

Any suggestions?

**Comment by hello-smile6** [comment]
@JaydenDev I could help, wait a moment. Currently running `npm install`

**Comment by hello-smile6** [comment]
@JaydenDev Finished install, looking at it. Just wondering, how do you feel about loading the Chromium system stylesheet for now, just to get a good color scheme?

**Comment by JaydenDev** [comment]
@hello-smile6 I'm fine with the userchrome.css configuration in config/

**Comment by hello-smile6** [comment]
> @hello-smile6 I'm fine with the userchrome.css configuration in config/

Could I import it from https://cursive.apps.chrome/chrome-apps-a4_202111181400_RC00_prod/a4_cros_stylesheet.css or somewhere? It'd just add environment variables for colors.

**Comment by JaydenDev** [comment]
Any CSS file will work with FreeCat, although the bloat might not be great :/. Maybe release it as an addon, or add it as an addon.

**Comment by hello-smile6** [comment]
> Any CSS file will work with FreeCat, although the bloat might not be great :/. Maybe release it as an addon, or add it as an addon.

If you'd be okay with it, I could add a build script that loads dependencies like that from a list, and uses empty files for dependencies that are not installed. Also, I'm wanting to make an installer. Would that be okay?

**Comment by JaydenDev** [comment]
An installer isn't needed, packages and binaries are easily available.

**Comment by hello-smile6** [comment]
> An installer isn't needed, packages and binaries are easily available.

Could I build binaries using https://npmjs.com/package/pkg ?

**Comment by JaydenDev** [comment]
DEB64, RPM64, DEB32, RPM32, RPMARM64, DEBARM64, EXE, and *.app files can be created with the build system

```bash
npm run make
```

**Comment by hello-smile6** [comment]
> DEB64, RPM64, DEB32, RPM32, RPMARM64, DEBARM64, EXE, and *.app files can be created with the build system
> 
> ```shell
> npm run make
> ```

What about packaged copies of dev builds?

**Comment by JaydenDev** [comment]
dev builds aren't priority for packaging.

**Comment by hello-smile6** [comment]
> dev builds aren't priority for packaging.

Oh.

**Comment by hello-smile6** [comment]
> 1. Make the search bar and go button on same line
> 
> Any suggestions?

Item 1 is fixed by #16 (Yes, I added `<!DOCTYPE html>` again, but test it first)

**Comment by JaydenDev** [comment]
The creator of the PR is required to test it, I don't want broken PRs being merged.

**Comment by hello-smile6** [comment]
> The creator of the PR is required to test it, I don't want broken PRs being merged.

I already tested it, but just don't want it ignored.

**Comment by JaydenDev** [comment]
testing PR now.

**Comment by JaydenDev** [comment]
Great UI, things are just wayyy too small

![image](https://user-images.githubusercontent.com/92550746/144946561-cda1ff55-6da8-4dbd-a2b7-08c412291e80.png)

**Comment by hello-smile6** [comment]
> Great UI, things are just wayyy too small
> 
> ![image](https://user-images.githubusercontent.com/92550746/144946561-cda1ff55-6da8-4dbd-a2b7-08c412291e80.png)

Okay. I'll have a fix in 10 minutes, hopefully. I'll also add environment variables to make UI size changes easier.

**Comment by JaydenDev** [comment]
Were you on a 1080p monitor?

**Comment by hello-smile6** [comment]
> Were you on a 1080p monitor?

Here's `screen`
```
Screen {availWidth: 1366, availHeight: 738, width: 1366, height: 768, colorDepth: 24, …}
availHeight: 738
availLeft: 0
availTop: 0
availWidth: 1366
colorDepth: 24
height: 768
orientation: ScreenOrientation
angle: 0
onchange: null
type: "landscape-primary"
[[Prototype]]: ScreenOrientation
pixelDepth: 24
width: 1366
[[Prototype]]: Screen
```

**Comment by JaydenDev** [comment]
Did you make the UI small by preference, or monitor config

**Comment by hello-smile6** [comment]
> Did you make the UI small by preference, or monitor config

Preference. I like small menus.

**Comment by JaydenDev** [comment]
Small menus can generally be bad, small UI = harder to read

**Comment by hello-smile6** [comment]
> Small menus can generally be bad, small UI = harder to read

Oh, I'll try to make it look better.

**Comment by JaydenDev** [comment]
i think half the size of a firefox tab is good

**Comment by hello-smile6** [comment]
> i think half the size of a firefox tab is good

Okay, I'll install Firefox (or check the source) and try to add that.

**Comment by JaydenDev** [comment]
![image](https://user-images.githubusercontent.com/92550746/144951012-1af34339-871a-4ed6-8145-4dfb2c7f4fef.png)

**Comment by hello-smile6** [comment]
> ![image](https://user-images.githubusercontent.com/92550746/144951012-1af34339-871a-4ed6-8145-4dfb2c7f4fef.png)

That'd be 36px, I think.

**Comment by JaydenDev** [comment]
half of the size?

**Comment by hello-smile6** [comment]
> half of the size?

18px. That's 2px less than my config.

**Comment by JaydenDev** [comment]
![image](https://user-images.githubusercontent.com/92550746/144952741-ff5b51c1-5cc3-4711-a3f0-28715aa1af96.png)
great so far

**Comment by hello-smile6** [comment]
> ![image](https://user-images.githubusercontent.com/92550746/144952741-ff5b51c1-5cc3-4711-a3f0-28715aa1af96.png) great so far

Since `env.css` is in `.gitignore`, there should be a `defaults.css` loaded before it so the UI doesn't look weird.

**Comment by hello-smile6** [comment]
Commenting from freecat!
![image](https://user-images.githubusercontent.com/73048226/144953033-564e415e-a539-4ae2-81f8-49d4a589f67e.png)

**Comment by hello-smile6** [comment]
@JaydenDev Could you enable GitHub Discussions?

**Comment by JaydenDev** [comment]
Yeah yeah, but discussions feels kinda bloated compared to the issues tab. Also more people are familiar with issues.

**Comment by JaydenDev** [comment]
does freecat handle cookies properly? do you stay logged in?

**Comment by hello-smile6** [comment]
> does freecat handle cookies properly? do you stay logged in?

Not sure, I assume it wouldn't.

**Comment by JaydenDev** [comment]
Would it be possible to implement a reload feature?

**Comment by hello-smile6** [comment]
> Yeah yeah, but discussions feels kinda bloated compared to the issues tab. Also more people are familiar with issues.

However, issues can quickly get off-topic. Also, it can get hard to decide when to close an issue that's more of a discussion. As an added reason, many websites related to github use the number of open issues to judge repository quality.

**Comment by JaydenDev** [comment]
soo... more issues = better software? doesn't really make sense

**Comment by hello-smile6** [comment]
> soo... more issues = better software? doesn't really make sense

It's just a factor they might consider. Also, it gets frustrating when people open issues that are just to ask questions about something.

**Comment by JaydenDev** [comment]
well this'll work for now, can't be puttin that much effort into a hobby project.

**Comment by hello-smile6** [comment]
> well this'll work for now, can't be puttin that much effort into a hobby project.

Why not? You just have to enable it in the repo settings, it takes less than 30 seconds. Also, this could go beyond a hobby project. Just look at https://beakerbrowser.org/ (another electron browser)

**Comment by JaydenDev** [comment]
who's gonna use a browser with barely any features made by a kid?

**Comment by hello-smile6** [comment]
> who's gonna use a browser with barely any features made by a kid?

It doesn't have to stop there. How about this?

> Who's going to use a browser with more features than Chromium that uses less memory, has bookmarklet APIs designed to allow full access to webpage contexts, and allows the JS stack, DOM, and element focus state to be saved to a file?

Everyone.
If you put the effort in, you'll get better results.

**Comment by JaydenDev** [comment]
I put plenty of effort in, it is just a HTML UI with web views after all.

**Comment by hello-smile6** [comment]
> I put plenty of effort in, it is just a HTML UI with web views after all.

It can be more. And it should become more over time.

**Comment by JaydenDev** [comment]
too many features want

requested features:
history

hard to implement

**Comment by hello-smile6** [comment]
> too many features people want
> 
> requested features: history
> 
> hard to implement

Think Electron webview API might help with that.

**Comment by JaydenDev** [comment]
Might push history from 1.1 to 1.2
and just implement reloading and call it a day

**Comment by hello-smile6** [comment]
> Might push history from 1.1 to 1.2 and just implement reloading and call it a day

I think I got history, testing right now.

**Comment by JaydenDev** [comment]
i could probobly just have a reload() function and have it reset the src part of the webview and have it reload

**Comment by hello-smile6** [comment]
> i could probobly just have a reload() function and have it reset the src part of the webview and have it reload

Or you could use the webview api.

**Comment by JaydenDev** [comment]
my ways are easier, but irrelevant and complicated

**Comment by hello-smile6** [comment]
> my ways are easier, but irrelevant and complicated. APIs are hard

I disagree. Reverse-engineering your own app is harder than just not `rm`ing your source,

**Comment by JaydenDev** [comment]
It doesn't all have to be in electron, I can just write my own framework and combine them

**Comment by hello-smile6** [comment]
> It doesn't all have to be in electron, I can just write my own framework and combine them. Just kidding

I know how! Wait a moment.

**Comment by JaydenDev** [comment]
```javascript
function reload() {
    document.getElementById("view").src="";
    document.getElementById("view").src=wsite;
}
```
```html
<button onClick="reload()">Reload Icon</button>
```

**Comment by JaydenDev** [comment]
Only 5 lines of code

**Comment by JaydenDev** [comment]
```javascript
function reload() {
    document.getElementById("view").src=wsite;
}
```
```html
<button onClick="reload()">Reload Icon</button>
```

shortened and optimized version

**Comment by hello-smile6** [comment]
> ```js
> function reload() {
>     document.getElementById("view").src=wsite;
> }
> ```
> 
> ```
> <button onClick="reload()">Reload Icon</button>
> ```
> 
> shortened and optimized version

Or, `addEventListener` and you can get rid of that CSP warning.

**Comment by JaydenDev** [comment]
uhh.. what's an addEventListener

**Comment by hello-smile6** [comment]
> uhh.. what's an addEventListener

```
domNode.addEventListener("click",function() {
  alert(1);
});
```

**Comment by JaydenDev** [comment]
THAT... is better than BUTTONS? hah

**Comment by JaydenDev** [comment]
buttons r kool

**Comment by hello-smile6** [comment]
> THAT... is better than BUTTONS? hah

Not better. Better than using onClick. Wait a moment and I'll make a demo.

**Comment by JaydenDev** [comment]
nothing is better than the one and only onClick, where is the evidence

**Comment by hello-smile6** [comment]
> nothing is better than the one and only onClick, where is the evidence

![image](https://user-images.githubusercontent.com/73048226/144957237-ac5921ac-8cf4-4557-bc14-0530b4b7a636.png)
onclick requires unsafe-eval to be enabled. Want to remove that warning? `addEventListener` is the way.

**Comment by JaydenDev** [comment]
I have to go, I'll be back. Get some clear evidence, and explain some differences between event listeners and onClick.
Once it  is decided whatever better one will be chosen

**Comment by hello-smile6** [comment]
> I have to go, I'll be back. Get some clear evidence, and explain some differences between event listeners and onClick. Once it is decided whatever better one will be chosen

Oh, I won't. I'll just implement it to show you. :)

**Comment by hello-smile6** [comment]
> I have to go, I'll be back. Get some clear evidence, and explain some differences between event listeners and onClick. Once it is decided whatever better one will be chosen

Told you! https://github.com/JaydenDev/freecat/pull/20

**Comment by JaydenDev** [comment]
your latest PR wont merge

**Comment by hello-smile6** [comment]
> your latest PR wont merge

I fixed it

**Comment by JaydenDev** [comment]
time to sort out who removed all those window titlebar options.
Some important features were removed:
Full screen
Developer Tools

**Comment by hello-smile6** [comment]
> time to sort out who removed all those window titlebar options. Some important features were removed: Full screen Developer Tools

I'll fix it.

**Comment by hello-smile6** [comment]
> time to sort out who removed all those window titlebar options. Some important features were removed: Full screen Developer Tools

Fixed by 19ed3fad0f0e15fa5c0417d21e7f471deac4cc4e

**Comment by hello-smile6** [comment]
@JaydenDev Are you okay?

**Comment by JaydenDev** [comment]
i was just playing terraria

**Comment by JaydenDev** [comment]
custom about menu... possible?

**Comment by hello-smile6** [comment]
> i was just playing terraria

What's that? Have you tried Scratcharia?
https://turbowarp.org/46587498/

**Comment by hello-smile6** [comment]
> custom about menu... possible?

I don't think so, unless custom implementations of everything in the title bar were made.

**Comment by webdev03** [comment]
Why are there hidden rickrolls?

**Comment by hello-smile6** [comment]
> Why are there hidden rickrolls? 🤣

What do you mean? What commit?

**Comment by webdev03** [comment]
Check in the main.js

**Comment by hello-smile6** [comment]
> Check in the main.js

Okay

**Comment by webdev03** [comment]
Uncaught Exception:
TypeError: app.whenReady is not a function

**Comment by hello-smile6** [comment]
Don't see anything.
[main.js](https://github.com/JaydenDev/freecat/blob/c786e236fb3e6d32ed09ac2dd43b5362a8bd29ec/app/main/main.js)

**Comment by hello-smile6** [comment]
> Uncaught Exception: TypeError: app.whenReady is not a function

I see an error from my menu removal (Fixing right now), but nothing else. Run `git pull`

**Comment by webdev03** [comment]
I fixed it

**Comment by hello-smile6** [comment]
> I fixed it

What commit added the problems?

**Comment by webdev03** [comment]
I think that the whenReady doesn't exist (where did you even get that from), as well as when removing the menu there was still 
`Menu.append(menu)` even though `menu` doesn't exist (it was commented out)

**Comment by hello-smile6** [comment]
> I think that the whenReady doesn't exist (where did you even get that from), as well as when removing the menu there was still `Menu.append(menu)` even though `menu` doesn't exist (it was commented out)

Oh, it exists for me. Run `npm update`

**Comment by webdev03** [comment]
Uncaught Exception:
TypeError: mainWindow.loadFile is not a function

**Comment by hello-smile6** [comment]
> Uncaught Exception: TypeError: mainWindow.loadFile is not a function

I think that's my fault, working on it.

**Comment by webdev03** [comment]
You sure?

**Comment by hello-smile6** [comment]
> 

It looks like it's real (used in dependencies). Not sure, looking into it.

**Comment by webdev03** [comment]
I swear, I have 
```js
app.on('ready', () => {
    globalShortcut.register('CommandOrControl+C', () => {
      shell.openExternal("https://youtu.be/dQw4w9WgXcQ");
    });
    globalShortcut.register("CommandOrControl+W", () => {
      shell.openExternal("https://youtu.be/dQw4w9WgXcQ");
    });
  globalShortcut.register("CommandOrControl+Shift+Esc", () => {
    shell.openExternal("https://youtu.be/dQw4w9WgXcQ");
  });
});
```
and it leads to a rickroll.

**Comment by hello-smile6** [comment]
> I swear, I have
> 
> ```js
> app.on('ready', () => {
>     globalShortcut.register('CommandOrControl+C', () => {
>       shell.openExternal("https://youtu.be/dQw4w9WgXcQ");
>     });
>     globalShortcut.register("CommandOrControl+W", () => {
>       shell.openExternal("https://youtu.be/dQw4w9WgXcQ");
>     });
>   globalShortcut.register("CommandOrControl+Shift+Esc", () => {
>     shell.openExternal("https://youtu.be/dQw4w9WgXcQ");
>   });
> });
> ```
> 
> and it leads to a rickroll. @JaydenDev I'm confused why you're saying this doesn't exist, at least it was there in an earlier commit

What commit added it, and what one removed it?

**Comment by JaydenDev** [comment]
continue in the discussions tab
