### ISSUE TITLE
Webview does not fill available space

### ISSUE THREAD

**Issue by hello-smile6** [JaydenDev/freecat#14]
![image](https://user-images.githubusercontent.com/73048226/144935151-a902161d-4ebe-49df-8219-edb1a8107c5c.png)
Is this supposed to happen? If not, I'd love to look into it. I have some experience with iframes that might translate over to Electron.
Environment: Windows, Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) freecat/1.0 Chrome/96.0.4664.55 Electron/16.0.4 Safari/537.36

**Comment by hello-smile6** [comment]
@JaydenDev Could I try to fix this?

**Comment by JaydenDev** [comment]
For me it works just fine, what is your freecat version?

**Comment by JaydenDev** [comment]
nope not working for me. your latest commit 'DOCTYPE something idk' broke it.

**Comment by hello-smile6** [comment]
> should work.. are you using a binary version or the npm ver

Gh, latest.

**Comment by hello-smile6** [comment]
> nope not working for me. your latest commit 'DOCTYPE something idk' broke it.

I'll work on a fix. It should be easy.

**Comment by JaydenDev** [comment]
I fixed it, your <!DOCTYPE HTML> broke it.

**Comment by JaydenDev** [comment]
Please test your PR before submission

**Comment by hello-smile6** [comment]
> Please test your PR before submission

Okay, I think it was because quirks mode was disabled. I'm trying to fix it right now.

**Comment by hello-smile6** [comment]
> I fixed it, your !DOCTYPE HTML broke it.

Seems like having a doctype declaration is the standard.
https://www.twilio.com/blog/an-introduction-to-building-desktop-applications-with-electron#:~:text=the%20following%20code%3A-,%3C!DOCTYPE%20html%3E,-%3Chtml%20lang%3D%22en
