### ISSUE TITLE
built-in light theme?

### ISSUE THREAD

**Issue by ScolderCreations** [JaydenDev/freecat#2]
Basically, an opposite of the existing UI theme, for light mode enjoyers.

Should I make this?

**Comment by JaydenDev** [comment]
Not sure this is possible with vanilla HTML/CSS/JS, can't use a framework for this. This is a software UI.

**Comment by JaydenDev** [comment]
also note the user is specifically directed to edit the userchrome.css in config/ to customize the UI.
