### ISSUE TITLE
The `app` directory still has the default auto-generated README.

### ISSUE THREAD

**Issue by MystPi** [JaydenDev/freecat#24]
I doesn't really matter that much.
https://github.com/JaydenDev/freecat/blob/main/app/README.md

**Comment by hello-smile6** [comment]
I'll fix it if you'd like. Could you assign it to me?

**Comment by MystPi** [comment]
> I'll fix it if you'd like. Could you assign it to me?

Sure.

**Comment by hello-smile6** [comment]
> > I'll fix it if you'd like. Could you assign it to me?
> 
> Sure. Edit: I can't, actually. Only @JaydenDev can.

@JaydenDev Could you?

**Comment by MystPi** [comment]
> > > I'll fix it if you'd like. Could you assign it to me?
> > 
> > 
> > Sure. Edit: I can't, actually. Only @JaydenDev can.
> 
> @JaydenDev Could you?

You don't have to be assigned to do it...

**Comment by hello-smile6** [comment]
> > > > I'll fix it if you'd like. Could you assign it to me?
> > > 
> > > 
> > > Sure. Edit: I can't, actually. Only @JaydenDev can.
> > 
> > 
> > @JaydenDev Could you?
> 
> You don't have to be assigned to do it...

Okay.

**Comment by JaydenDev** [comment]
fixed.
