### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by hello-smile6** [JaydenDev/freecat#25]
I do not have an icon for freecat

_Originally posted by @JaydenDev in https://github.com/JaydenDev/freecat/issues/17#issuecomment-987456846_
Could someone make one?

**Comment by webdev03** [comment]
I'm working on a few designs

**Comment by hello-smile6** [comment]
> I'm working on a few designs

Could I see?

**Comment by webdev03** [comment]
![image](https://user-images.githubusercontent.com/75148774/145126124-39f4c360-466a-4083-a5ef-40032526c257.png)
Do you like this one? I have a few more designs too.

**Comment by hello-smile6** [comment]
> ![image](https://user-images.githubusercontent.com/75148774/145126124-39f4c360-466a-4083-a5ef-40032526c257.png) Do you like this one? I have a few more designs too.

Nice! @JaydenDev What do you think?

**Comment by webdev03** [comment]
I'm working on a few, I hope to have at least 5 soon and maybe in a zip file, I can also provide SVG as I made it in Google Drawings

**Comment by webdev03** [comment]
My one would look quite small, though, should it just be a big "F" instead of the full name?

**Comment by webdev03** [comment]
https://user-images.githubusercontent.com/75148774/145126999-9b4b3c65-241c-4785-9897-a1ef71b36ba7.png
https://user-images.githubusercontent.com/75148774/145127121-ce6b703f-74ba-436b-bb5b-5eb837994cae.png
more coming soon, probably in a zip file

**Comment by JaydenDev** [comment]
a bit smaller as well...?

**Comment by JaydenDev** [comment]
preferred 32x32 or 64x64, standard icon sizes

**Comment by webdev03** [comment]
Oh, okay, I'll make it 64x64

**Comment by hello-smile6** [comment]
<img src="https://user-images.githubusercontent.com/75148774/145126999-9b4b3c65-241c-4785-9897-a1ef71b36ba7.png">
<img src="https://user-images.githubusercontent.com/75148774/145127121-ce6b703f-74ba-436b-bb5b-5eb837994cae.png">
Here's previews.

**Comment by webdev03** [comment]
Ahhh!! I made them all 500x500!! I have to reconvert them all

**Comment by webdev03** [comment]
[freecat logos.zip](https://github.com/JaydenDev/freecat/files/7672476/freecat.logos.zip)

**Comment by hello-smile6** [comment]
> [freecat logos.zip](https://github.com/JaydenDev/freecat/files/7672476/freecat.logos.zip)

Nice! Removed the __MACOSX directory.
[freecat logos.zip](https://github.com/JaydenDev/freecat/files/7672489/freecat.logos.zip)

**Comment by JaydenDev** [comment]
seconds.svg downsized to 32x32 will work

**Comment by webdev03** [comment]
OK! I will do that!

**Comment by webdev03** [comment]
@hello-smile6 sorry, I use a mac, I'm not sure where that came from lol

**Comment by JaydenDev** [comment]
once your down make a PR that makes electron use the logo.

**Comment by webdev03** [comment]
OK!
I'd give it to you but for some reason Github isn't accepting the file, then I'll try to make that work.

**Comment by hello-smile6** [comment]
> once your down make a PR that makes electron use the logo.

I could do that.

**Comment by webdev03** [comment]
Working on it.. please wait..

**Comment by webdev03** [comment]
Can someone else do it? I am having trouble getting it to work.

**Comment by hello-smile6** [comment]
> Can someone else do it? I am having trouble getting it to work.

Let me try. Could you make a PR with your icons in `app/icons` on my fork?

**Comment by webdev03** [comment]
You can unzip the zip file, those are the icons I think

**Comment by hello-smile6** [comment]
> You can unzip the zip file, those are the icons I think

Okay

**Comment by webdev03** [comment]
**Please give credit if Freecat uses these I worked hard**

**Comment by hello-smile6** [comment]
> **Please give credit if Freecat uses these I worked hard**

Okay.

**Comment by JaydenDev** [comment]
Added credit to README.

**Comment by JaydenDev** [comment]
has it been added to the repo?

**Comment by webdev03** [comment]
No, I'm not sure how to do it.

**Comment by hello-smile6** [comment]
Let's figure out how https://github.com/microsoft/vscode does icons.

**Comment by hello-smile6** [comment]
@JaydenDev How did I do?

**Comment by JaydenDev** [comment]
A feature aint good
til it works on linux

Please consider all 3 platforms:
Win/Mac/Linux

**Comment by hello-smile6** [comment]
> A feature isn't good until it works on Linux.
> 
> Please consider all 3 platforms: Win/Mac/Linux

I know. The docs just don't make sense.

**Comment by webdev03** [comment]
Which logo are you using?

**Comment by hello-smile6** [comment]
> Which logo are you using?

Currently, none.

**Comment by webdev03** [comment]
Oh ok then how would you implement it without an icon? Can you make one?

**Comment by hello-smile6** [comment]
> Oh ok then how would you implement it without an icon? Can you make one?

Could you upload some blank icons of the same sizes?

**Comment by webdev03** [comment]
I don't know if Electron even accepts blank images.

**Comment by JaydenDev** [comment]
you all had a backup of your icons right? If not they might be in the unstable branch.

**Comment by webdev03** [comment]
I don't want the icons to be used @JaydenDev so please don't use the backup...

**Comment by JaydenDev** [comment]
you don't want the icon used... cool. I wont use it, you can make your own fork of FreeCat if you want.
