### ISSUE TITLE
App UI won't show up

### ISSUE THREAD

**Issue by hello-smile6** [JaydenDev/freecat#27]
I think the HTML file might be broken

**Comment by hello-smile6** [comment]
I think it was because of https://github.com/JaydenDev/freecat/commit/2c50ac65fe534c0b1d53ab489438c593b8130a6f and my bad merge work.

**Comment by JaydenDev** [comment]
please fix it soon, I don't know what your PR does so I cant fix it

**Comment by hello-smile6** [comment]
> please fix it soon, I don't know what your PR does so I cant fix it

I think it's because @ScolderCreations 's PR was merged before mine.

**Comment by JaydenDev** [comment]
@ScolderCreations has caused 2 bugs so far

**Comment by hello-smile6** [comment]
> @ScolderCreations has caused 2 bugs so far

Doesn't sound good.

**Comment by webdev03** [comment]
#33 should fix it

**Comment by hello-smile6** [comment]
> #33 should fix it

I closed my PR (#34), yours is better.

**Comment by JaydenDev** [comment]
this is resolved
