### ISSUE TITLE
Set up Prettier (and maybe eslint)

### ISSUE THREAD

**Issue by webdev03** [JaydenDev/freecat#37]
Prettier will make the code look consistent and we can enforce semicolons or double/one quote(s) and it will make a much more even codebase. Also, when you format the file, less merge conflicts will happen. ESLint, if you really want to be strict, will allow us to enforce the Prettier rules to make a much more even codebase. I can try to make this if you would like.

**Comment by webdev03** [comment]
(by the way, this can be a dev dependency, so I don't think it will impact the size of production builds)

**Comment by hello-smile6** [comment]
Sounds like a good idea, could I help? And could a test script (and maybe automatic corrections using GitHub Actions) be added?

**Comment by webdev03** [comment]
Test script, I have a bit of experience with jest...

**Comment by hello-smile6** [comment]
> Test script, I have a bit of experience with jest...

Okay, want to work on it on a fork?

**Comment by webdev03** [comment]
If we're going this route, we could just implement TypeScript but I don't do much Electron development, so I don't know if that is possible.

**Comment by hello-smile6** [comment]
> If we're going this route, we could just implement TypeScript but I don't do much Electron development, so I don't know if that is possible.

I tried TypeScript once. It's too hard to configure, and takes a lot of time to compile. Tests could likely accomplish the same goal.

**Comment by webdev03** [comment]
> I tried TypeScript once. It's too hard to configure, and takes a lot of time to compile. Tests could likely accomplish the same goal.
I use typescript for my project and it works well, let's not get too offtopic.

If you don't know prettier there is https://prettier.io/ which can give some basic instructions.

**Comment by hello-smile6** [comment]
> > I tried TypeScript once. It's too hard to configure, and takes a lot of time to compile. Tests could likely accomplish the same goal.
> 
> I use typescript for my project and it works well, let's not get too offtopic.
> 
> If you don't know prettier there is https://prettier.io/ which can give some basic instructions.

Okay, I'll give you access to my fork and we can work on it.

**Comment by webdev03** [comment]
> Okay, I'll give you access to my fork and we can work on it.

I'm not giving my IP address, why do you want it?

**Comment by hello-smile6** [comment]
> > Okay, I'll give you access to my fork and we can work on it.
> 
> I'm not giving my IP address, why do you want it?

I don't want it. Just use pull requests instead, then.

**Comment by hello-smile6** [comment]
> > Okay, I'll give you access to my fork and we can work on it.
> 
> I'm not giving my IP address, why do you want it?

I wish there was a way to disable that.

**Comment by JaydenDev** [comment]
what...?

**Comment by JaydenDev** [comment]
bloat = bad

**Comment by hello-smile6** [comment]
> bloat = bad

It won't make the repo bigger.

**Comment by webdev03** [comment]
Bloat? It will make it easier for newcomers to come as there isn't going to be, let's say, some people loving `function` syntax while others like the new Arrow functions. @JaydenDev **please** rethink this.

**Comment by hello-smile6** [comment]
> Bloat? It will make it easier for newcomers to come as there isn't going to be, let's say, some people loving `function` syntax while others like the new Arrow functions. @JaydenDev **please** rethink this.

Please!

**Comment by webdev03** [comment]
You know, I'll fork it myself and do it.

**Comment by hello-smile6** [comment]
> You know, I'll fork it myself and do it.

I'll just contribute on your fork from now on.

**Comment by webdev03** [comment]
I did it.

**Comment by JaydenDev** [comment]
This PR is too big for more precise reviewing to make sure no bad code

**Comment by webdev03** [comment]
It is formatted, you can check it, all I did was add prettier and format all the code.

**Comment by webdev03** [comment]
Thanks 😄
