### ISSUE TITLE
Make freecat easier to work with

### ISSUE THREAD

**Issue by webdev03** [JaydenDev/freecat#44]
Normally, in projects, we can do `npm install` first on the directory we cloned, but in Freecat, we have to cd into the app folder first. I don't think this is a monorepo so I think that it would be fine if the npm scripts pointed to `app`.

**Comment by webdev03** [comment]
I can try to do this after the Prettier PR gets merged.

**Comment by hello-smile6** [comment]
> I can try to do this after the Prettier PR gets merged.

I'll see if I could make passthrough binaries for different platforms in the root directory.

**Comment by webdev03** [comment]
> > I can try to do this after the Prettier PR gets merged.
> 
> I'll see if I could make passthrough binaries for different platforms in the root directory.

?

**Comment by hello-smile6** [comment]
> > > I can try to do this after the Prettier PR gets merged.
> > 
> > 
> > I'll see if I could make passthrough binaries for different platforms in the root directory.
> 
> ?

`npm` binaries that `cd` into `app/` and run `npm`.

**Comment by JaydenDev** [comment]
binaries dont go in the repository, only in releases.

**Comment by webdev03** [comment]
I mean to say, then you can run `npm install` in the directory you cloned without CD into the `app/` directory.

**Comment by JaydenDev** [comment]
The app is in app/, repository information, licensing, and run scripts go in /

**Comment by webdev03** [comment]
The thing is that Prettier is a dev dependency just like Electron and the others (excluding electron-forge I think) so that wouldn't be possible without #44

**Comment by webdev03** [comment]
Okay, I've managed to do this, should I PR in?

**Comment by hello-smile6** [comment]
> Okay, I've managed to do this, @JaydenDev should I PR? Now Prettier can run on the MD files if you want.

Go for it~!

**Comment by webdev03** [comment]
@JaydenDev close this because you closed #47

**Comment by hello-smile6** [comment]
> @JaydenDev close this because you closed #47

Please don't close this.

**Comment by JaydenDev** [comment]
done.

**Comment by webdev03** [comment]
By the way, your version of my changes just broke Freecat, change the "main" kin package.json to point to the right file.

**Comment by webdev03** [comment]
Also, the CI is broken too. Please fix that.

**Comment by hello-smile6** [comment]
> Also, the CI is broken too. Please fix that.

Run `git pull`
