### ISSUE TITLE
Fix Freecat, like literally please fix it

### ISSUE THREAD

**Issue by webdev03** [JaydenDev/freecat#48]
You can't run Freecat anymore since when making https://github.com/JaydenDev/freecat/commit/3e31ddac766919fd9d685065027883b31fdfbd02 the "main" in package.json hasn't been changed to fit this which has broken Freecat. I have a new idea: **Test your commits before pushing them to main branch** or **staging**.

**Comment by JaydenDev** [comment]
the issue has to do with me forgetting to change main/main.js to app/main/main.js, fixing

**Comment by webdev03** [comment]
OK! Can you also merge my PR which puts the Prettier files in the root directory to make Prettier work?

**Comment by webdev03** [comment]
Also, the CI is broken - you'll need to fix that

**Comment by JaydenDev** [comment]
there are no PRs available rn
Idk what CI is

**Comment by webdev03** [comment]
CI is the Github actions. My PR that you closed actually did this correctly.

**Comment by webdev03** [comment]
For reference, #47 is the PR that is closed.

**Comment by JaydenDev** [comment]
It seemed like a risky PR, what changes did you make exactly.
What is the CI for? What does it do? If it forces people to use a utility im removing it

**Comment by webdev03** [comment]
No, it's the Github actions that checks if they run the Prettier, it doesn't force anything it's just to help you.

**Comment by hello-smile6** [comment]
> It seemed like a risky PR, what changes did you make exactly. What is the CI for? What does it do? If it forces people to use a utility im removing it

It helps make sure that the code is understandable and helps avoid broken commits. It's not required, but I'd encourage it, as it'd also catch failed merges.

**Comment by JaydenDev** [comment]
I will have to revert freecat to a working build, a PR must of broke it.

**Comment by JaydenDev** [comment]
I dont know why it doesn't run, so I cant fix it.

**Comment by webdev03** [comment]
**Your commit broke it!!!**

**Comment by hello-smile6** [comment]
> I will have to revert freecat to a working build, a PR must of broke it.

Revert whatever you just did. My fork has a working configuration. I have an open PR (#43) that will fix it.
