### ISSUE TITLE
FreeCat doesn't run

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#50]
```npm start``` returns

Error launching app
Unable to find Electron app at /home/JaydenDev/GitHub/freecat/app

Cannot find module '/home/JaydenDev/GitHub/freecat/app'
Require stack:
- /usr/local/lib/node_modules/electron/dist/resources/default_app.asar/main.js

**Comment by webdev03** [comment]
How many of these same types of errors we have had? I thought my PR had fixed 100% of them and works, why do we need not working version Freecat?

**Comment by JaydenDev** [comment]
check the package.json and package-lock.json maybe the problem is their

**Comment by hello-smile6** [comment]
> `npm start` returns
> 
> Error launching app Unable to find Electron app at /home/JaydenDev/GitHub/freecat/app
> 
> Cannot find module '/home/JaydenDev/GitHub/freecat/app' Require stack:
> 
> * /usr/local/lib/node_modules/electron/dist/resources/default_app.asar/main.js

@JaydenDev Removed confidential info from your issue, hope you don't mind.

**Comment by webdev03** [comment]
I should have fixed it.

**Comment by JaydenDev** [comment]
unlike most i dont care if my name gets seen lol

**Comment by JaydenDev** [comment]
also adding you both as collaborators made it way easier, I no longer have to merge every PR myself

**Comment by webdev03** [comment]
Ok!

**Comment by hello-smile6** [comment]
> also adding you both as collaborators made it way easier, I no longer have to merge every PR myself

Could I add a `user-error` tag for issues created because someone forgot to `git pull` or something?
