### ISSUE TITLE
Make a new branch for every version

### ISSUE THREAD

**Issue by ninjamar** [JaydenDev/freecat#58]
Make a new branch for every release

**Comment by webdev03** [comment]
Isn't that what Git tags are for?

**Comment by webdev03** [comment]
(Oh sorry you mean a branch for staging each version?)

**Comment by ninjamar** [comment]
For every release

**Comment by ninjamar** [comment]
> I like that, a branch so that changes can be easily made to older versions. However, can we keep `main` as the main branch?

yes

**Comment by webdev03** [comment]
@hello-smile6 I have an idea: the source code already comes as a ZIP in Github releases.

**Comment by hello-smile6** [comment]
> @hello-smile6 I have an idea: the source code already comes as a ZIP in Github releases.

Yes?

**Comment by webdev03** [comment]
Yes, so why don't they just download the ZIP? I think this is a good idea, but I am not sure if it is already done and we don't need to redo what github does.

**Comment by JaydenDev** [comment]
no version branches
their already are zips for every single build in GH releases.

**Comment by ninjamar** [comment]
> no version branches their already are zips for every single build in GH releases.

It gets easier to see. What if there is a bug in an old version that needs to be fixed?

**Comment by hello-smile6** [comment]
> > no version branches their already are zips for every single build in GH releases.
> 
> It gets easier to see. What if there is a bug in an old version that needs to be fixed?

Yes! I agree.
