### ISSUE TITLE
Binaries don't work

### ISSUE THREAD

**Issue by hello-smile6** [JaydenDev/freecat#70]
# Command-line output:

```
C:\Users\hello-smile6\Documents\GitHub\freecat>npm run make

> freecat@1.0.0 make
> electron-forge make

✔ Checking your system
✔ Resolving Forge Config
We need to package your application before we can make it
✔ Preparing to Package Application for arch: x64
✔ Preparing native dependencies
✔ Packaging Application
Making for the following targets: squirrel
✔ Making for target: squirrel - On platform: win32 - For arch: x64
```

# OS and dependency versions:
## Windows:
```
Microsoft Windows [Version 10.0.19042.985]
```
## Node:
```
v16.13.1
```
## NPM:
```
8.1.2
```

# Other information
## Screenshot
![screenshot](https://user-images.githubusercontent.com/73048226/145500756-f29e614c-e486-46da-8208-75c0bb0cfe37.png)

**Comment by hello-smile6** [comment]
> It's a known issue that EXE binaries dont work properly, in fact none of them do. They all have the same error, deb64 rpm64 and win64

I'll try to fix it.

**Comment by JaydenDev** [comment]
you'll have to fix it for Win/Mac/Linux

**Comment by hello-smile6** [comment]
> you'll have to fix it for Win/Mac/Linux

If I'm right, it'll take less than 30 seconds.

**Comment by hello-smile6** [comment]
Well, I was right. Unfortunately, I introduced another bug. I'll fix that, then we'll finally have some binaries!

**Comment by hello-smile6** [comment]
@JaydenDev Told you!

**Comment by JaydenDev** [comment]
#70 and #71 are related in ways, dont close any tho

**Comment by hello-smile6** [comment]
Testing.

**Comment by JaydenDev** [comment]
```
TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined
    at checkListener (node:events:131:3)
    at _addListener (node:events:427:3)
    at App.addListener (node:events:491:10)
    at Object.<anonymous> (/home/jmwills/GitHub/freecat/main/main.js:73:5)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at loadApplicationPackage (/usr/local/lib/node_modules/electron/dist/resources/default_app.asar/main.js:110:16)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined
    at checkListener (node:events:131:3)
    at _addListener (node:events:427:3)
    at App.addListener (node:events:491:10)
    at Object.<anonymous> (/home/jmwills/GitHub/freecat/main/main.js:73:5)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at loadApplicationPackage (/usr/local/lib/node_modules/electron/dist/resources/default_app.asar/main.js:110:16)

```

**Comment by JaydenDev** [comment]
```
__   __                  _                      _             _   _         
\ \ / /   ___    _   _  | |__    _ __    ___   | | __   ___  (_) | |_       
 \ V /   / _ \  | | | | | '_ \  | '__|  / _ \  | |/ /  / _ \ | | | __|      
  | |   | (_) | | |_| | | |_) | | |    | (_) | |   <  |  __/ | | | |_ _ _ _ 
  |_|    \___/   \__,_| |_.__/  |_|     \___/  |_|\_\  \___| |_|  \__(_|_|_)
                                                                            

```

**Comment by hello-smile6** [comment]
> ```
> __   __                  _                      _             _   _         
> \ \ / /   ___    _   _  | |__    _ __    ___   | | __   ___  (_) | |_       
>  \ V /   / _ \  | | | | | '_ \  | '__|  / _ \  | |/ /  / _ \ | | | __|      
>   | |   | (_) | | |_| | | |_) | | |    | (_) | |   <  |  __/ | | | |_ _ _ _ 
>   |_|    \___/   \__,_| |_.__/  |_|     \___/  |_|\_\  \___| |_|  \__(_|_|_)
>                                                                             
> ```

Run this:
```shell
sudo npm i -g node@latest npm@latest npx@latest
sudo apt update
npm update
```
Does it still happen? It works for me.

**Comment by JaydenDev** [comment]
gotta
 w
   o
     r
          k

on

L   i       n        u        x

**Comment by hello-smile6** [comment]
> gotta w o r k
> 
> on
> 
> L i n u x

gotta
u
p
d
a
t
e

y o u r
O
S

See if that works. Also, try doing `git pull` again.

**Comment by JaydenDev** [comment]
You are not cooperating like a good collaborator would.
Just because it works for you, that's not an excuse to not fix it on other systems :(

**Comment by hello-smile6** [comment]
> You are not cooperating like a good collaborator would. Just because it works for you, that's not an excuse to not fix it on other systems :(

Never mind, didn't work for me. I fixed it, there was a problem with it because I forgot to rewrite something.

**Comment by hello-smile6** [comment]
@JaydenDev Figured it out, about to merge once I test.

**Comment by hello-smile6** [comment]
Fixed by https://github.com/JaydenDev/freecat/commit/98c4542f61e6274cf9aae5124b02f042e498c341, let's celebrate!
