### ISSUE TITLE
you broke it.

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#71]
You must depend on an EXACT version of "electron-prebuilt-compile" not a range (got "^1.8.2")

you broke it

**Comment by webdev03** [comment]
I broke it?

**Comment by JaydenDev** [comment]
someone broke it.

**Comment by webdev03** [comment]
Well, your error message explains exactly what happened by the way. You need to depend on an exact version of "electron-prebuilt-compile" not a range (got "^1.8.2")

**Comment by webdev03** [comment]
Also, by the way, I think you should follow the contributing style rules you made...

**Comment by JaydenDev** [comment]
i didnt make it
plus templates are bloat
don't want bloat in my issues :)

**Comment by hello-smile6** [comment]
> i didnt make it plus templates are bloat don't want bloat in my issues :)

The template helped me create an issue faster.

**Comment by webdev03** [comment]
you have eslint and prettier

**Comment by webdev03** [comment]
Change the line in package.json to https://github.com/JaydenDev/freecat/pull/7/commits/0d2639a0b9320d1bdd5306cbcf746a1fccc664d8#diff-012b982f97a0d326aeec58dd3b789484b05a944d609afe1b8ed5e299fc485f61R26
