### ISSUE TITLE
What's .upm and dist/

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#73]
explain yourselves, what the heck.

**Comment by hello-smile6** [comment]
I was using https://github.com/replit/upm and an alternative Electron build package. The .upm directory should stay in my opinion because it has configuration files for it.

**Comment by JaydenDev** [comment]
electron-forge > mysterious bloat.

**Comment by hello-smile6** [comment]
> electron-forge > mysterious bloat.

It's also by the electron devs. Also, the app works for me.

**Comment by JaydenDev** [comment]
Again... "works for you" doesn't matter.
Are you the only one using it? no
Have you pushed your fixes?
I get very much frustrated with the "works for me" I hate it, stop using that phrase its stupid and selfish.

**Comment by hello-smile6** [comment]
> Again... "works for you" doesn't matter. Are you the only one using it? no Have you pushed your fixes? I get very much frustrated with the "works for me" I hate it, stop using that phrase its stupid and selfish.

I have pushed my fixes. What exactly won't work?

**Comment by hello-smile6** [comment]
> Again... "works for you" doesn't matter. Are you the only one using it? no Have you pushed your fixes? I get very much frustrated with the "works for me" I hate it, stop using that phrase its stupid and selfish.

I'll use https://www.onworks.net/ and test on one of its VMs.

**Comment by hello-smile6** [comment]
I found that nodejs could not even be installed on it, so I could not get results.
