### ISSUE TITLE
Stop closing this issue, FreeCat still doesn't work.

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#74]
Find an actual solution, someone.

**Comment by hello-smile6** [comment]
Works for me.

**Comment by JaydenDev** [comment]
you keep installing very much unneeded modules every time i go to test if something's broke...
you don't tell me about the new dependencies either.

**Comment by JaydenDev** [comment]
btw the UI doesn't load...

**Comment by hello-smile6** [comment]
> you keep installing very much unneeded modules every time i go to test if something's broke... you don't tell me about the new dependencies either.

I'll test.
