### ISSUE TITLE
interface doesn't load... again

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#75]
blank screen
brightness
whiteness
nothingness
broken application-once-again-ness

**Comment by hello-smile6** [comment]
> blank screen brightness whiteness nothingness broken application-once-again-ness

I'll look.

**Comment by JaydenDev** [comment]
"With a strict framework, comes pain"

**Comment by JaydenDev** [comment]
stop commenting on closed issues...

**Comment by JaydenDev** [comment]
#77
