### ISSUE TITLE
FreeCat has hit a major issue, someone fix so FreeCat can continue development.

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#77]
Interface doesn't load

**Comment by hello-smile6** [comment]
> Interface doesn't load

I cannot reproduce. However, it seems like the `apt` package repository servers may be down.

**Comment by hello-smile6** [comment]
> Interface doesn't load

What is the specific error?

**Comment by hello-smile6** [comment]
> Interface doesn't load

I'll start reverting commits that may have caused it on my on different branches on my fork. Maybe something got messed up.

**Comment by JaydenDev** [comment]
I only clone from the 'main' branch.
Test your commits on the 'testing' branch
Once tested, move them to the 'main' branch where I test them

You are unaware of the new branch system, that's my fault.

**Comment by JaydenDev** [comment]
https://github.com/JaydenDev/freecat/releases/tag/2112901
is the latest build confirmed working.

**Comment by hello-smile6** [comment]
> I only clone from the 'main' branch. Test your commits on the 'testing' branch Once tested, move them to the 'main' branch where I test them
> 
> You are unaware of the new branch system, that's my fault.

Okay. I have an idea. I'll try making it use the `whenReady` version for Linux, but the `app.on("ready")` version for other platforms.

**Comment by JaydenDev** [comment]
ok, maybe that'll do somethin

**Comment by hello-smile6** [comment]
> ok, maybe that'll do somethin

I'll try it.

**Comment by JaydenDev** [comment]
some branches that still work

hello-smile6-add-icon-windows-1 
hello-smile6-patch-3
hello-smile6-patch-2
hello-smile6-patch-1

the only branches that aren't working

main
testing

**Comment by hello-smile6** [comment]
> some branches that still work
> 
> hello-smile6-add-icon-windows-1 hello-smile6-patch-3 hello-smile6-patch-2 hello-smile6-patch-1
> 
> the only branches that aren't working
> 
> main testing

Strange. Are there any errors? What happens if you download a .zip and install?

**Comment by JaydenDev** [comment]
i told you that the latest zipped build that works is 
https://github.com/JaydenDev/freecat/releases/tag/2112901

the reason the branches work and some dont is that they aren't all on the same commit/ up to date.

**Comment by hello-smile6** [comment]
> i told you that the latest zipped build that works is https://github.com/JaydenDev/freecat/releases/tag/2112901
> 
> the reason the branches work and some dont is that they aren't all on the same commit/ up to date.

Okay. What version of node are you using? Node 17 is broken.

**Comment by JaydenDev** [comment]
v16.11.1

**Comment by hello-smile6** [comment]
Wait, I think I know why! Terminate all Electron and Node processes, then try again. Does it work?

**Comment by JaydenDev** [comment]
It's a problem with FreeCat not Node or Electron.
Please find a fix, soon. Gotta release 1.1 eventually :/

**Comment by hello-smile6** [comment]
> It's a problem with FreeCat not Node or Electron. Please find a fix, soon. Gotta release 1.1 eventually :/

Okay. Does 98c4542f61e6274cf9aae5124b02f042e498c341 work?

**Comment by JaydenDev** [comment]
n o p e

**Comment by JaydenDev** [comment]
still no UI

**Comment by JaydenDev** [comment]
revert to the latest commit in the add-icon branch (revert main obv)
since its the latest working code we have.

**Comment by JaydenDev** [comment]
errors in the code is being found at 
https://github.com/JaydenDev/freecat/security/code-scanning
automatically.. cool.
look there

**Comment by JaydenDev** [comment]
nobody is working on the issue... freecat will stay broken forever.

**Comment by hello-smile6** [comment]
> nobody is working on the issue... freecat will stay broken forever.

It won't.

**Comment by JaydenDev** [comment]
i've seen no commits... wdym.

**Comment by JaydenDev** [comment]
ima revert all commits after the latest commit of the add-icon branch.

**Comment by JaydenDev** [comment]
done...
