### ISSUE TITLE
WebLoad tag not working

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#8]
Problem: app/index.html
Line: Botton
Type: Web Load
Problem: Not loading home.html

I have not yet found a fix.

**Comment by Darth-Ness** [comment]
Can you detail what you've tried? Maybe try adding home.html to the src?

**Comment by MystPi** [comment]
If you mean the `webview` tag, you must enable it first.
```js
webPreferences: {
  webviewTag: true
}
```
https://github.com/MystPi/ninetails/blob/7d0acc5f4a33d704ad32b4204a929959d55b5c38/src/index.js#L17-L19

**Comment by ScolderCreations** [comment]
yeah if you merge the pr i just linked it will work

**Comment by JaydenDev** [comment]
still broken

**Comment by JaydenDev** [comment]
oh it works just fine, just the URL functions aren't

**Comment by MystPi** [comment]
> still broken

Make sure you're using `webview` instead of `webload` (whatever that is).

**Comment by JaydenDev** [comment]
webload is the function that modifies the webview to use the input from the search box

**Comment by JaydenDev** [comment]
Works! the webview just doesn't take all available room

**Comment by MystPi** [comment]
> Works! the webview just doesn't take all available room

Just resize it with CSS, then you should be good-to-go.

**Comment by JaydenDev** [comment]
thankyou everyone! i will be releasing 1.0-prerelease-1 soon

**Comment by JaydenDev** [comment]
gotta wrap up the website

**Comment by JaydenDev** [comment]
*release
