### ISSUE TITLE
Why did you merge the PRs to the wrong branches

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#82]
@hello-smile6

**Comment by JaydenDev** [comment]
now freecat is broken once again

**Comment by hello-smile6** [comment]
What error?

**Comment by JaydenDev** [comment]
no undo your PR merges, thats the solution. Stop breaking things, currently behind schedule on the 2.0 or 1.1 releaseeee

**Comment by hello-smile6** [comment]
> no undo your PR merges, thats the solution. Stop breaking things, currently behind schedule on the 2.0 or 1.1 releaseeee

Okay.

**Comment by JaydenDev** [comment]
the two PRs that needa be reverted are called "Testing" and "Unstable"

**Comment by hello-smile6** [comment]
Trying

**Comment by JaydenDev** [comment]
i see what you did

you merged main into testing
and main into unstable

when it was supposed to be 
PR "Testing" > unstable
PR "unstable" > testing.

**Comment by JaydenDev** [comment]
you deleted the entire repository, I'm removing you from collaborators.

**Comment by hello-smile6** [comment]
> 

Actually, everything went to main.

**Comment by JaydenDev** [comment]
the repo is empty

**Comment by JaydenDev** [comment]
i CANT revert it there is no button

**Comment by hello-smile6** [comment]
> the repo is empty

I'm trying to get it fixed

**Comment by hello-smile6** [comment]
> i CANT revert it there is no button

Making a PR to revert it

**Comment by hello-smile6** [comment]
See #83

**Comment by JaydenDev** [comment]
I'm keeping complete control of the flow of PRs, since you seem to be going too crazy and breaking things without some moderation.

**Comment by JaydenDev** [comment]
I'm resetting all FreeCat development back to 1.0

**Comment by hello-smile6** [comment]
> 

Sorry, I'll try to fix it

**Comment by JaydenDev** [comment]
Alright I have a clean slate known as 1.0
Now, remember your mistakes don't make em again.
it's all good, lets make 2.0

**Comment by JaydenDev** [comment]
@hello-smile6 please read

**Comment by JaydenDev** [comment]
gotta make tons of features from scratch but it'll work in the end
