### ISSUE TITLE
Webview not taking all space

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#84]
Fixed previously, but needs re fixing after the reset.

**Comment by JaydenDev** [comment]
fixed

**Comment by JaydenDev** [comment]
not :(

**Comment by hello-smile6** [comment]
FINE. Yes, I made #85 , but I'll try to get it to work.

**Comment by JaydenDev** [comment]
ok, im having a hard time back porting features

**Comment by hello-smile6** [comment]
> 

I'll help.

**Comment by JaydenDev** [comment]
Remember

Features and Bug Fixes > Automatic Repository Maintainence

**Comment by JaydenDev** [comment]
how to fix...?

**Comment by JaydenDev** [comment]
fixed in a PR
