### ISSUE TITLE
2.0 features

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#94]
New UI, dream.css implementation
Bug Fixes

tabs pls :) help tabs idk how to tab tabs

**Comment by JaydenDev** [comment]
testing issue comments with gh cli﻿

**Comment by hello-smile6** [comment]
@JaydenDev I got tabs, I think.

**Comment by JaydenDev** [comment]
ok﻿

**Comment by hello-smile6** [comment]
> ok

I just learned how to make a GitHub workspace file for a configuration, should I commit it?

**Comment by JaydenDev** [comment]
what exactly is a workspace, is it needed?﻿

**Comment by hello-smile6** [comment]
> what exactly is a workspace, is it needed?

It just adds a JSON file like this which tells VSCode how to set up the editor environment.
```
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {}
}
```
Then, everyone'd have the same vscode configuration.

**Comment by JaydenDev** [comment]
thats useless when they can just import the folder



or use vim :)﻿

**Comment by hello-smile6** [comment]
> thats useless when they can just import the folder
> 
> or use vim :)

I'm just going to say it, `vim` is junk. It's nearly impossible to close.
Also, there might be a specific configuration you want people to use someday. That'd allow you to set things like that.

**Comment by hello-smile6** [comment]
Are you going to merge the `testing` branch into `main`?

**Comment by JaydenDev** [comment]
what do you expect? its a CLI text editor if you cant even CLI then dont use it. Its easy :w to write :q to close omg is it that hard?﻿

**Comment by JaydenDev** [comment]
testing branch goes through excessive testing before going into main to be packaged as a dev build

**Comment by hello-smile6** [comment]
> what do you expect? its a CLI text editor if you cant even CLI then dont use it. Its easy :w to write :q to close omg is it that hard?

Wait, `:w` to write? Also, `nano`'s easier.

**Comment by hello-smile6** [comment]
> testing branch goes through excessive testing before going into main to be packaged as a dev build

But it works! Try it!

**Comment by JaydenDev** [comment]
i have to go, i'll take a look at it tomarrow﻿

**Comment by hello-smile6** [comment]
> i have to go, i'll take a look at it tomarrow

Okay.

**Comment by hello-smile6** [comment]
> New UI, dream.css implementation Bug Fixes
> 
> tabs pls :) help tabs idk how to tab tabs

Think it's ironic that Freecat's using `@MystPi`'s CSS library, while still not having the same UI as their electron browser.

**Comment by JaydenDev** [comment]
i dont remember who added the css library.
I have half-decent UI design, and that's really an overstatement.

**Comment by hello-smile6** [comment]
> i dont remember who added the css library. I have half-decent UI design, and that's really an overstatement.

It was me, in case your wondering. Isn't their stylesheet pretty?

**Comment by JaydenDev** [comment]
I CAN make modern UI design in fact FreeCat already HAD modern UI design.

**Comment by hello-smile6** [comment]
> I CAN make modern UI design in fact FreeCat already HAD modern UI design.

I agree. Also, why not just use the URL change code from Ninetails to update the URL shown? I noticed that they have that done.

**Comment by JaydenDev** [comment]
since the URL bar is a literal <input> tag that isn't possible.
unless the website src the webview is set to can be used to change the text in the input bar..
OH MY GOD
it is

Find a way to set the text of the URL bar to whatever the webview src is set to

**Comment by hello-smile6** [comment]
> since the URL bar is a literal tag that isn't possible. unless the website src the webview is set to can be used to change the text in the input bar.. OH MY GOD it is
> 
> Find a way to set the text of the URL bar to whatever the webview src is set to

Simple. Check out https://github.com/MystPi/ninetails/blob/b7ee7b7a518cafa76822437f259841a39f3932fc/src/browser.js#L208

**Comment by JaydenDev** [comment]
the UI is made in HTML not javascript

**Comment by hello-smile6** [comment]
> the UI is made in HTML not javascript

That's how you run code every time the page URL in the webview changes.

**Comment by JaydenDev** [comment]
this is purely an aesthetic feature
I need FreeCat to not be a dumpster fire first

**Comment by hello-smile6** [comment]
> this is purely an aesthetic feature I need FreeCat to not be a dumpster fire first

What do you mean? Also, I got it. Making a PR.

**Comment by JaydenDev** [comment]
FreeCat and its code is an unstable feature-lacking dumpster fire
Even Ninetails (a kinda direct competitor)  has more features and its been around for a shorter amount of time

**Comment by JaydenDev** [comment]
the "random browser made by a scratcher" market is a race to the finish.

**Comment by hello-smile6** [comment]
> FreeCat and its code is an unstable feature-lacking dumpster fire Even Ninetails (a kinda direct competitor) has more features and its been around for a shorter amount of time

Well, most of the Ninetails features could be added in under 2 hours. Also, does the `testing` branch work?

**Comment by hello-smile6** [comment]
Never mind.

**Comment by hello-smile6** [comment]
Also, it works. We have dynamic URL updating.

**Comment by JaydenDev** [comment]
ima merge it to testing

**Comment by hello-smile6** [comment]
Testing it to make sure it works well.

**Comment by JaydenDev** [comment]
ok

**Comment by hello-smile6** [comment]
Haven't made a commit yet.

**Comment by JaydenDev** [comment]
ok

if you use FreeCat, you understand the dumpster fire

**Comment by hello-smile6** [comment]
> ok
> 
> if you use FreeCat, you understand the dumpster fire

I know what you mean. Also, I got a video of the URL bar update feature.

https://user-images.githubusercontent.com/73048226/146273106-23b4adc2-b711-48c1-a2cd-82f6a0eb9a5a.mp4

**Comment by JaydenDev** [comment]
No video with supported format and MIME type found

**Comment by hello-smile6** [comment]
> No video with supported format and MIME type found

What? Do you not have an MP4 codec?

**Comment by JaydenDev** [comment]
i might not im on linux after all
i think its a GH issue

**Comment by hello-smile6** [comment]
> i might not im on linux after all i think its a GH issue

Try downloading and running it using bash, that should open a video player which can play it.
https://user-images.githubusercontent.com/73048226/146273106-23b4adc2-b711-48c1-a2cd-82f6a0eb9a5a.mp4

**Comment by hello-smile6** [comment]
See #97

**Comment by JaydenDev** [comment]
I installed all the codecs and libraries needed and it still doesn't show

**Comment by hello-smile6** [comment]
> I installed all the codecs and libraries needed and it still doesn't show

Try downloading a Chromium build from https://download-chromium.appspot.com/ or installing `chromium-browser` using your package manager, Chromium might work.

**Comment by JaydenDev** [comment]
no #firefoxftw

**Comment by JaydenDev** [comment]
btw i can just run sudo dnf install chromium and be done with it
#linuxftw

**Comment by hello-smile6** [comment]
> btw i can just run sudo dnf install chromium and be done with it #linuxftw

Wish I could do that. Seriously. I don't use Windows because I want to, just saying.

**Comment by JaydenDev** [comment]
last thing we need
tabs
then i can apply some patches and release 2.0

**Comment by JaydenDev** [comment]
Features are already decided and being worked on
