### ISSUE TITLE
Why did I get removed on the contributors list?

### ISSUE THREAD

**Issue by snowcatridge10** [JaydenDev/freecat#95]

**Comment by JaydenDev** [comment]
It might of been an error with the script, I will rerun the action soon.﻿

**Comment by webdev03** [comment]
There's a limit on how many people go on that list.

**Comment by hello-smile6** [comment]
> There's a limit on how many people go on that list.

Oh! (Could you please come back?)

**Comment by JaydenDev** [comment]
resolved
