### ISSUE TITLE
Built packages and binaries dont run

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#96]
many users are reporting built packages and binaries not running
might be an issue with the build system implemented
it works for Ninetails﻿

**Comment by hello-smile6** [comment]
Does the `testing` branch work? If not, what's the error?

**Comment by JaydenDev** [comment]
im talking about binaries and build systems the code itself is fine.

**Comment by hello-smile6** [comment]
> im talking about binaries and build systems the code itself is fine.

I'll try building for win32. Will give results once I have them.

**Comment by JaydenDev** [comment]
it affects all platforms Linux-all-architectures Win32/64 Mac32/64

**Comment by JaydenDev** [comment]
and MacM*arm64

**Comment by hello-smile6** [comment]
Okay, let's make a checklist of platforms to test then.

- [x] Win32-x64 (Successful build at https://personal-server.9pfs.repl.co/freecat-1.0.0%20Setup.exe)
- [ ] win32-x32
- [ ] Linux-x64-`.deb`
- [ ] Linux-x64-`.rpm`
- [ ] MacOS-x64
- [ ] MacOS-arm64

**Comment by JaydenDev** [comment]
so was the issue fixed... somehow...?

**Comment by hello-smile6** [comment]
> so was the issue fixed... somehow...?

Don't know, all I know is that I got a successful build on my `url-bar-update` branch.

**Comment by JaydenDev** [comment]
no i mean they build fine, but do they run...?

**Comment by hello-smile6** [comment]
> no i mean they build fine, but do they run...?

Yes. Try that one I shared in a Windows 10 VM or using `wine`. It runs.

**Comment by JaydenDev** [comment]
![image](https://user-images.githubusercontent.com/92550746/146277942-5d4f0a9d-926e-4973-b569-eb8d0ba7606f.png)

**Comment by hello-smile6** [comment]
> ![image](https://user-images.githubusercontent.com/92550746/146277942-5d4f0a9d-926e-4973-b569-eb8d0ba7606f.png)

Will fix. Give me about 2 minutes.

**Comment by hello-smile6** [comment]
@JaydenDev Try building again on `testing`. Cannot find that, and those locations do not exist-- There are only 54 lines, and line 35 is a comment.

**Comment by JaydenDev** [comment]
May be a directory issue

**Comment by JaydenDev** [comment]
Please contribute to the electron-forge implementation of Catalyst instead
https://github.com/JaydenDev/Catalyst
