### ISSUE TITLE
Hey, we gotta wrap up and release 2.0

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#99]
Add tabs real quick make em stable and we're ready.

**Comment by hello-smile6** [comment]
I'll see if I can take the tabs code from ninetails and get something working.

**Comment by JaydenDev** [comment]
hey hey stealing bad
i dont want this to be a 35% ninetails fork

**Comment by hello-smile6** [comment]
> hey hey stealing bad i dont want this to be a 35% ninetails fork

I'm just using things that we could do ourselves and are too small to make a difference.

**Comment by JaydenDev** [comment]
ok, ima fix the broken search icon while u do that

**Comment by hello-smile6** [comment]
> ok, ima fix the broken search icon while u do that

I thought I fixed that...

**Comment by hello-smile6** [comment]
> ok, ima fix the broken search icon while u do that

Already fixed. Just checked.

**Comment by JaydenDev** [comment]
oh i needed to npm install

**Comment by JaydenDev** [comment]
fixed it

**Comment by JaydenDev** [comment]
make it to where when its showing the home page it doesn't show a long string in the search bar

file:///home/jmwills/GitHub/freecat/home.html
isn't aesthetically pleasing.

**Comment by hello-smile6** [comment]
> make it to where when its showing the home page it doesn't show a long string in the search bar
> 
> file:///home/jmwills/GitHub/freecat/home.html isn't aesthetically pleasing.

Okay, will do. Should be easy.

**Comment by JaydenDev** [comment]
maybe have it show "home" on the home page?

**Comment by JaydenDev** [comment]
also for non-URLs (searching) can it use a search engine like DDG?

**Comment by hello-smile6** [comment]
> maybe have it show "home" on the home page?

Working on it, just need to figure out how we can send the URL of the homepage to the renderer process.

**Comment by hello-smile6** [comment]
> also for non-URLs (searching) can it use a search engine like DDG?

Sure. Wanna just use the Ninetails code for that (or maybe slightly modified)? :)

**Comment by JaydenDev** [comment]
COPYING CODE
FROM COMPETITORS
teRrIble PraCticES

**Comment by hello-smile6** [comment]
> COPYING CODE FROM COMPETITORS teRrIble PraCticES

It's FOSS! Why not? Anyways, it wouldn't take much to implement some of the same omnibox behavior as Chromium.

**Comment by hello-smile6** [comment]
Think I figured it out.

**Comment by JaydenDev** [comment]
It is referred to as the URL bar, the nav bar (holding all the icons like search and reload).

**Comment by hello-smile6** [comment]
> It is referred to as the URL bar, the nav bar (holding all the icons like search and reload).

I know. Also, I don't have the homepage URL showing for me. I'll work on that.

**Comment by hello-smile6** [comment]
#101 partially fixes the homepage problem. It might fix it entirely soon.

**Comment by webdev03** [comment]
You all really need to use Prettier if you spent so much time setting it up but don't format or do anything with your code.

**Comment by JaydenDev** [comment]
#100 
btw @webdev03 prettier ruins code.
